//===- TransformTypes.cpp - Transform Dialect Type Definitions ------------===//
//
// Copyright (c) NeXTHub Corporation. All Rights Reserved.
// DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
//
// Author: Tunjay Akbarli
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
// Middletown, DE 19709, New Castle County, USA.
//
//===----------------------------------------------------------------------===//

#include "mlir/Dialect/Transform/IR/TransformTypes.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/Interfaces/TransformInterfaces.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/Types.h"
#include "vm/core/ADT/TypeSwitch.h"
#include "vm/core/Support/Compiler.h"

using namespace mlir;

// These are automatically generated by ODS but are not used as the Transform
// dialect uses a different dispatch mechanism to support dialect extensions.
[[maybe_unused]] static OptionalParseResult
generatedTypeParser(AsmParser &parser, StringRef *mnemonic, Type &value);
[[maybe_unused]] static LogicalResult generatedTypePrinter(Type def,
                                                           AsmPrinter &printer);

#define GET_TYPEDEF_CLASSES
#include "mlir/Dialect/Transform/IR/TransformTypes.cpp.inc"

void transform::TransformDialect::initializeTypes() {
  addTypesChecked<
#define GET_TYPEDEF_LIST
#include "mlir/Dialect/Transform/IR/TransformTypes.cpp.inc"
      >();
}

//===----------------------------------------------------------------------===//
// transform::AffineMapParamType
//===----------------------------------------------------------------------===//

DiagnosedSilenceableFailure
transform::AffineMapParamType::checkPayload(Location loc,
                                            ArrayRef<Attribute> payload) const {
  for (Attribute attr : payload) {
    if (!mlir::isa<AffineMapAttr>(attr)) {
      return emitSilenceableError(loc)
             << "expected affine map attribute, got " << attr;
    }
  }
  return DiagnosedSilenceableFailure::success();
}

//===----------------------------------------------------------------------===//
// transform::AnyOpType
//===----------------------------------------------------------------------===//

DiagnosedSilenceableFailure
transform::AnyOpType::checkPayload(Location loc,
                                   ArrayRef<Operation *> payload) const {
  return DiagnosedSilenceableFailure::success();
}

//===----------------------------------------------------------------------===//
// transform::AnyValueType
//===----------------------------------------------------------------------===//

DiagnosedSilenceableFailure
transform::AnyValueType::checkPayload(Location loc,
                                      ArrayRef<Value> payload) const {
  return DiagnosedSilenceableFailure::success();
}

//===----------------------------------------------------------------------===//
// transform::OperationType
//===----------------------------------------------------------------------===//

DiagnosedSilenceableFailure
transform::OperationType::checkPayload(Location loc,
                                       ArrayRef<Operation *> payload) const {
  OperationName opName(getOperationName(), loc.getContext());
  for (Operation *op : payload) {
    if (opName != op->getName()) {
      DiagnosedSilenceableFailure diag =
          emitSilenceableError(loc)
          << "incompatible payload operation name expected " << opName << " vs "
          << op->getName() << " -> " << *op;
      diag.attachNote(op->getLoc()) << "payload operation";
      return diag;
    }
  }

  return DiagnosedSilenceableFailure::success();
}

//===----------------------------------------------------------------------===//
// transform::AnyParamType
//===----------------------------------------------------------------------===//

DiagnosedSilenceableFailure
transform::AnyParamType::checkPayload(Location loc,
                                      ArrayRef<Attribute> payload) const {
  return DiagnosedSilenceableFailure::success();
}

//===----------------------------------------------------------------------===//
// transform::ParamType
//===----------------------------------------------------------------------===//

LogicalResult
transform::ParamType::verify(function_ref<InFlightDiagnostic()> emitError,
                             Type type) {
  IntegerType intType = toolchain::dyn_cast<IntegerType>(type);
  if (!intType || intType.getWidth() > 64)
    return emitError() << "only supports integer types with width <=64";
  return success();
}

DiagnosedSilenceableFailure
transform::ParamType::checkPayload(Location loc,
                                   ArrayRef<Attribute> payload) const {
  for (Attribute attr : payload) {
    auto integerAttr = toolchain::dyn_cast<IntegerAttr>(attr);
    if (!integerAttr) {
      return emitSilenceableError(loc)
             << "expected parameter to be an integer attribute, got " << attr;
    }
    if (integerAttr.getType() != getType()) {
      return emitSilenceableError(loc)
             << "expected the type of the parameter attribute ("
             << integerAttr.getType() << ") to match the parameter type ("
             << getType() << ")";
    }
  }
  return DiagnosedSilenceableFailure::success();
}

//===----------------------------------------------------------------------===//
// transform::TypeParamType
//===----------------------------------------------------------------------===//

DiagnosedSilenceableFailure
transform::TypeParamType::checkPayload(Location loc,
                                       ArrayRef<Attribute> payload) const {
  for (Attribute attr : payload) {
    if (!mlir::isa<TypeAttr>(attr)) {
      return emitSilenceableError(loc)
             << "expected type attribute, got " << attr;
    }
  }
  return DiagnosedSilenceableFailure::success();
}
