/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

// Autogenerated file by wrong_ctx_tests.rb script -- DO NOT EDIT!

#include "libabckit/c/abckit.h"
#include "libabckit/c/metadata_core.h"
#include "libabckit/c/extensions/arkts/metadata_arkts.h"
#include "libabckit/c/extensions/js/metadata_js.h"
#include "libabckit/c/ir_core.h"

#include "helpers/helpers.h"
#include "helpers/helpers_wrong_ctx.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_arktsModifyApiImp = AbckitGetArktsModifyApiImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitWrongCtxTestsArktsModifyApiImpl0 : public ::testing::Test {};

// Test: test-kind=api, api=ArktsModifyApiImpl::moduleAddImportFromArktsV1ToArktsV1,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsModifyApiImpl0, moduleAddImportFromArktsV1ToArktsV1)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsModifyApiImp->moduleAddImportFromArktsV1ToArktsV1);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::moduleAddExportFromArktsV1ToArktsV1,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsModifyApiImpl0, moduleAddExportFromArktsV1ToArktsV1)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsModifyApiImp->moduleAddExportFromArktsV1ToArktsV1);
}

}  // namespace libabckit::test
