/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

// Autogenerated file by wrong_ctx_tests.rb script -- DO NOT EDIT!

#include "libabckit/c/abckit.h"
#include "libabckit/c/metadata_core.h"
#include "libabckit/c/extensions/arkts/metadata_arkts.h"
#include "libabckit/c/extensions/js/metadata_js.h"
#include "libabckit/c/ir_core.h"

#include "helpers/helpers.h"
#include "helpers/helpers_wrong_ctx.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_arktsInspectApiImp = AbckitGetArktsInspectApiImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitWrongCtxTestsArktsInspectApiImpl0 : public ::testing::Test {};

// Test: test-kind=api, api=ArktsInspectApiImpl::arktsClassToCoreClass,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, arktsClassToCoreClass)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->arktsClassToCoreClass);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::coreAnnotationToArktsAnnotation,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, coreAnnotationToArktsAnnotation)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->coreAnnotationToArktsAnnotation);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::arktsModuleToCoreModule,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, arktsModuleToCoreModule)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->arktsModuleToCoreModule);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::arktsAnnotationInterfaceFieldToCoreAnnotationInterfaceField,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, arktsAnnotationInterfaceFieldToCoreAnnotationInterfaceField)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->arktsAnnotationInterfaceFieldToCoreAnnotationInterfaceField);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::arktsFunctionToCoreFunction,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, arktsFunctionToCoreFunction)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->arktsFunctionToCoreFunction);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::coreExportDescriptorToArktsExportDescriptor,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, coreExportDescriptorToArktsExportDescriptor)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->coreExportDescriptorToArktsExportDescriptor);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::coreNamespaceToArktsNamespace,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, coreNamespaceToArktsNamespace)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->coreNamespaceToArktsNamespace);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::coreImportDescriptorToArktsImportDescriptor,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, coreImportDescriptorToArktsImportDescriptor)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->coreImportDescriptorToArktsImportDescriptor);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::arktsImportDescriptorToCoreImportDescriptor,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, arktsImportDescriptorToCoreImportDescriptor)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->arktsImportDescriptorToCoreImportDescriptor);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::arktsAnnotationElementToCoreAnnotationElement,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, arktsAnnotationElementToCoreAnnotationElement)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->arktsAnnotationElementToCoreAnnotationElement);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::coreModuleToArktsModule,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, coreModuleToArktsModule)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->coreModuleToArktsModule);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::arktsAnnotationInterfaceToCoreAnnotationInterface,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, arktsAnnotationInterfaceToCoreAnnotationInterface)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->arktsAnnotationInterfaceToCoreAnnotationInterface);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::arktsNamespaceToCoreNamespace,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, arktsNamespaceToCoreNamespace)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->arktsNamespaceToCoreNamespace);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::coreClassToArktsClass,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, coreClassToArktsClass)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->coreClassToArktsClass);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::arktsExportDescriptorToCoreExportDescriptor,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, arktsExportDescriptorToCoreExportDescriptor)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->arktsExportDescriptorToCoreExportDescriptor);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::coreAnnotationInterfaceFieldToArktsAnnotationInterfaceField,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, coreAnnotationInterfaceFieldToArktsAnnotationInterfaceField)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->coreAnnotationInterfaceFieldToArktsAnnotationInterfaceField);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::coreAnnotationInterfaceToArktsAnnotationInterface,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, coreAnnotationInterfaceToArktsAnnotationInterface)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->coreAnnotationInterfaceToArktsAnnotationInterface);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::arktsV1NamespaceGetConstructor,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, arktsV1NamespaceGetConstructor)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->arktsV1NamespaceGetConstructor);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::arktsAnnotationToCoreAnnotation,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, arktsAnnotationToCoreAnnotation)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->arktsAnnotationToCoreAnnotation);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::coreFunctionToArktsFunction,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, coreFunctionToArktsFunction)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->coreFunctionToArktsFunction);
}

// Test: test-kind=api, api=ArktsInspectApiImpl::coreAnnotationElementToArktsAnnotationElement,
// abc-kind=NoABC, category=negative-file
TEST_F(LibAbcKitWrongCtxTestsArktsInspectApiImpl0, coreAnnotationElementToArktsAnnotationElement)
{
    helpers_wrong_ctx::TestWrongCtx(g_arktsInspectApiImp->coreAnnotationElementToArktsAnnotationElement);
}

}  // namespace libabckit::test
