@startuml
class CoroutineManager {
    + Launch(Method entrypoint, List arguments)
    + Schedule()
    + Unblock(Coroutine coro)
    + Schedule()
    + Await(Promise promise)
    + Terminate(Coroutine coro)
    
    - Suspend(Coroutine coro)
    - Resume(Coroutine coro)

    - JobQueue job_queue
    - List<Coroutine> wait_list
    - List<Coroutine> ready_to_run_list
    - Coroutine running_coroutine
}
@enduml


