@startuml
interface JobQueue {
    + put(Promise, Coroutine)
}

class JSMicroJobQueue {
    + put(Promise, Coroutine)
    + map(Promise, JSPromise)
    + getJsPromise(Promise)

    -Map<Promise, JSPromise> promise_map
}

JobQueue <-- JSMicroJobQueue

@enduml
