#!/bin/bash
# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
ARK_ROOT=$SCRIPT_DIR/..
ARK_THIRD_PARTY_DIR=$ARK_ROOT/third_party
GN_PATH=$ARK_THIRD_PARTY_DIR/prebuilts/build-tools/linux-x86/bin/gn

if [ ! -d $GN_PATH ]; then
    $SCRIPT_DIR/install-arkcompiler-toolchain-prebuilts
fi

cd $ARK_ROOT
$GN_PATH gen out --args="is_standard_system=true ark_ets_interop_js=true"
ninja -C out arkts_bin ark_aot ets2panda verifier_bin ets_interop_js_napi
