#!/bin/bash
# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
ARK_ROOT=$SCRIPT_DIR/..
ARK_THIRD_PARTY_DIR=$ARK_ROOT/third_party
PREBUILTS_DOWNLOAD_SCRIPT=$ARK_THIRD_PARTY_DIR/prebuilts_download.sh

if [ ! -d "${ARK_THIRD_PARTY_DIR}/prebuilts" ]; then
    if [ ! -f ${PREBUILTS_DOWNLOAD_SCRIPT} ]; then
        ln -s ${ARK_THIRD_PARTY_DIR}/build/prebuilts_download/prebuilts_download.sh $PREBUILTS_DOWNLOAD_SCRIPT
    fi

    cd $ARK_THIRD_PARTY_DIR && $PREBUILTS_DOWNLOAD_SCRIPT
    rm -rf $ARK_ROOT/openharmony_prebuilts
fi
