#!/bin/bash
#===----------------------------------------------------------------------===#
#   Copyright (c) NeXTHub Corporation. All Rights Reserved.
#   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
#   Author: Tunjay Akbarli
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
#   Middletown, DE 19709, New Castle County, USA.
#===----------------------------------------------------------------------===#

mkdir -p /opt/ohos-sdk && \
curl -Lo /opt/ohos-sdk-windows_linux-public.tar.gz -q https://mirrors.huaweicloud.com/harmonyos/os/5.0.0-Release/ohos-sdk-windows_linux-public.tar.gz && \
tar -xzf /opt/ohos-sdk-windows_linux-public.tar.gz -C /opt/ohos-sdk && \
unzip -q /opt/ohos-sdk/linux/native-linux-x64-5.0.0.71-Release.zip -d /opt/ohos-sdk && \
unzip -q /opt/ohos-sdk/linux/toolchains-linux-x64-5.0.0.71-Release.zip -d /opt/ohos-sdk && \
ln -s /opt/ohos-sdk/toolchains/hdc /usr/local/bin/hdc && \
rm -fr /opt/ohos-sdk-windows_linux-public.tar.gz
