#===----------------------------------------------------------------------===#
#   Copyright (c) NeXTHub Corporation. All Rights Reserved.
#   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
#   Author: Tunjay Akbarli
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
#   Middletown, DE 19709, New Castle County, USA.
#===----------------------------------------------------------------------===#
[project]
name = "URunner-2"


[tool.ruff]
target-version = "py310"
preview = true
line-length = 120

exclude = [
  ".git",
  "__pycache__",
  "venv",
  "build",
  "dist",
]

# - E,
# - F: flake8
# - B: bugbear
# - UP: pyupgrade
# - I: isort
# - RUF - specific rules

lint.select = ["E", "F", "B", "UP", "I", "RUF"]


lint.ignore = [
  "D100",  # missing-module-docstring
  "D101",  # missing-class-docstring
  "D102",  # missing-function-docstring
  "B008",  # too-many-instance-attributes
  "B006",  # too-many-arguments
  "T201",  # logging-format-interpolation
  "B027",  # too-few-public-methods
  "UP009", # ignore encoding
  "RUF052",
]

