/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

// Autogenerated file by gen_null_arg_tests.rb script -- DO NOT EDIT!

#include "libabckit/c/abckit.h"
#include "libabckit/c/ir_core.h"
#include "libabckit/c/isa/isa_dynamic.h"
#include "libabckit/c/isa/isa_static.h"

#include "helpers/helpers_mode.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_isaApiStaticImp = AbckitGetIsaApiStaticImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitWrongModeTestsIsaApiStaticImpl0 : public ::testing::Test {};

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateAShr,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateAShr)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateAShr, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateAShrI,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateAShrI)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateAShrI, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateAdd,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateAdd)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateAdd, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateAddI,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateAddI)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateAddI, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateAnd,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateAnd)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateAnd, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateAndI,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateAndI)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateAndI, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateCallStatic,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateCallStatic)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateCallStatic, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateCallVirtual,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateCallVirtual)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateCallVirtual, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateCast,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateCast)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateCast, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateCheckCast,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateCheckCast)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateCheckCast, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateCmp,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateCmp)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateCmp, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateDiv,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateDiv)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateDiv, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateDivI,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateDivI)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateDivI, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateEquals,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateEquals)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateEquals, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateStrictEquals,
// abc-kind=NoABC, category=negative-mode
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateStrictEquals)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateStrictEquals, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateIf,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateIf)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateIf, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateInitObject,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateInitObject)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateInitObject, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateIsInstance,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateIsInstance)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateIsInstance, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateIsUndefined,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateIsUndefined)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateIsUndefined, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateLenArray,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateLenArray)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateLenArray, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateLoadArray,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateLoadArray)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateLoadArray, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateLoadConstArray,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateLoadConstArray)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateLoadConstArray, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateLoadString,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateLoadString)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateLoadString, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateLoadNullValue,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateLoadNullValue)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateLoadNullValue, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateMod,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateMod)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateMod, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateModI,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateModI)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateModI, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateMul,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateMul)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateMul, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateMulI,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateMulI)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateMulI, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateNeg,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateNeg)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateNeg, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateNewArray,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateNewArray)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateNewArray, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateNewObject,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateNewObject)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateNewObject, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateNot,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateNot)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateNot, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateOr,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateOr)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateOr, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateOrI,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateOrI)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateOrI, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateReturn,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateReturn)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateReturn, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateReturnVoid,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateReturnVoid)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateReturnVoid, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateShl,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateShl)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateShl, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateShlI,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateShlI)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateShlI, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateShr,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateShr)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateShr, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateShrI,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateShrI)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateShrI, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateStoreArray,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateStoreArray)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateStoreArray, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateStoreArrayWide,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateStoreArrayWide)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateStoreArrayWide, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateLoadObject,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateLoadObject)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateLoadObject, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateSub,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateSub)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateSub, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateSubI,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateSubI)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateSubI, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateThrow,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateThrow)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateThrow, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateXor,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateXor)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateXor, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateXorI,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateXorI)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateXorI, false);
}

// Test: test-kind=api, api=IsaApiStaticImpl::iCreateStoreObject,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiStaticImpl0, iCreateStoreObject)
{
    helpers_mode::TestMode(g_isaApiStaticImp->iCreateStoreObject, false);
}

}  // namespace libabckit::test