/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

// Autogenerated file by gen_null_arg_tests.rb script -- DO NOT EDIT!

#include "libabckit/c/abckit.h"
#include "libabckit/c/ir_core.h"
#include "libabckit/c/isa/isa_dynamic.h"
#include "libabckit/c/isa/isa_static.h"

#include "helpers/helpers_mode.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_isaApiDynamicImp = AbckitGetIsaApiDynamicImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitWrongModeTestsIsaApiDynamicImpl1 : public ::testing::Test {};

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdthisbyvalue,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdthisbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdthisbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdtrue,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdtrue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdtrue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdundefined,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLdundefined)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLdundefined, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLess,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLess)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLess, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLesseq,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLesseq)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLesseq, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLoadString,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateLoadString)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateLoadString, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateMod2,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateMod2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateMod2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateMul2,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateMul2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateMul2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNeg,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateNeg)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNeg, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewlexenv,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateNewlexenv)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNewlexenv, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewlexenvwithname,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateNewlexenvwithname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNewlexenvwithname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewobjapply,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateNewobjapply)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNewobjapply, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewobjrange,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateNewobjrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNewobjrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNot,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateNot)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNot, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNoteq,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateNoteq)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateNoteq, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateOr2,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateOr2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateOr2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreatePoplexenv,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreatePoplexenv)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreatePoplexenv, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateResumegenerator,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateResumegenerator)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateResumegenerator, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateReturn,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateReturn)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateReturn, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateReturnundefined,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateReturnundefined)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateReturnundefined, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSetgeneratorstate,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateSetgeneratorstate)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSetgeneratorstate, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSetobjectwithproto,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateSetobjectwithproto)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSetobjectwithproto, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateShl2,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateShl2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateShl2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateShr2,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateShr2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateShr2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStarrayspread,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStarrayspread)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStarrayspread, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStglobalvar,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStglobalvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStglobalvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStlexvar,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStlexvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStlexvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStmodulevar,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyindex,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStobjbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStobjbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyname,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStobjbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStobjbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyvalue,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStobjbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStobjbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyindex,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStownbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStownbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyname,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStownbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStownbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbynamewithnameset,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStownbynamewithnameset)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStownbynamewithnameset, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyvalue,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStownbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStownbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyvaluewithnameset,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStownbyvaluewithnameset)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStownbyvaluewithnameset, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStprivateproperty,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStprivateproperty)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStprivateproperty, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStricteq,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStricteq)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStricteq, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStrictnoteq,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStrictnoteq)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStrictnoteq, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStsuperbyname,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStsuperbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStsuperbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStsuperbyvalue,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStsuperbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStsuperbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStthisbyname,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStthisbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStthisbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStthisbyvalue,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateStthisbyvalue)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateStthisbyvalue, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSub2,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateSub2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSub2, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallarrowrange,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateSupercallarrowrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSupercallarrowrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallspread,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateSupercallspread)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSupercallspread, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallthisrange,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateSupercallthisrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSupercallthisrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSuspendgenerator,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateSuspendgenerator)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateSuspendgenerator, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTestin,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateTestin)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTestin, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrow,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrow)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrow, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowConstassignment,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowConstassignment)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowConstassignment, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowDeletesuperproperty,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowDeletesuperproperty)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowDeletesuperproperty, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowIfnotobject,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowIfnotobject)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowIfnotobject, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowIfsupernotcorrectcall,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowIfsupernotcorrectcall)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowIfsupernotcorrectcall, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowNotexists,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowNotexists)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowNotexists, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowPatternnoncoercible,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowPatternnoncoercible)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowPatternnoncoercible, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowUndefinedifhole,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowUndefinedifhole)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowUndefinedifhole, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowUndefinedifholewithname,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateThrowUndefinedifholewithname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateThrowUndefinedifholewithname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTonumber,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateTonumber)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTonumber, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTonumeric,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateTonumeric)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTonumeric, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTryldglobalbyname,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateTryldglobalbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTryldglobalbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTrystglobalbyname,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateTrystglobalbyname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTrystglobalbyname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTypeof,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateTypeof)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateTypeof, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCallrange,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideCallrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideCallrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCallthisrange,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideCallthisrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideCallthisrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCopyrestargs,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideCopyrestargs)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideCopyrestargs, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCreateobjectwithexcludedkeys,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideCreateobjectwithexcludedkeys)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideCreateobjectwithexcludedkeys, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideGetmodulenamespace,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideGetmodulenamespace)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideGetmodulenamespace, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdexternalmodulevar,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideLdexternalmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideLdexternalmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdlexvar,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideLdlexvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideLdlexvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdlocalmodulevar,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideLdlocalmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideLdlocalmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdobjbyindex,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideLdobjbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideLdobjbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdpatchvar,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideLdpatchvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideLdpatchvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewlexenv,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideNewlexenv)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideNewlexenv, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewlexenvwithname,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideNewlexenvwithname)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideNewlexenvwithname, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewobjrange,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideNewobjrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideNewobjrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStlexvar,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideStlexvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideStlexvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStmodulevar,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideStmodulevar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideStmodulevar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStobjbyindex,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideStobjbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideStobjbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStownbyindex,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideStownbyindex)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideStownbyindex, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStpatchvar,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideStpatchvar)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideStpatchvar, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideSupercallarrowrange,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideSupercallarrowrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideSupercallarrowrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideSupercallthisrange,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateWideSupercallthisrange)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateWideSupercallthisrange, true);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateXor2,
// abc-kind=NoABC, category=negative-mode, extension=c
TEST_F(LibAbcKitWrongModeTestsIsaApiDynamicImpl1, iCreateXor2)
{
    helpers_mode::TestMode(g_isaApiDynamicImp->iCreateXor2, true);
}

}  // namespace libabckit::test