/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

include "ModuleFormat.fbs";

namespace BCHIRFormat;

file_identifier "BIR2";

struct CodePosition {
  file: uint32;
  line: uint32; // line
  col: uint32;  // column
}

struct PosAnnotation {
  index: uint32;
  codePosition: CodePosition;
}

// Just used in debug mode.
struct ChirIDAnnotation {
  index: uint32;
  // the original CHIR node ID
  chidNodeId: uint64;
}

table TType {
  //All the different types are flattened
  kind:uint8; // TypeKind static casted to an unsigned int
  // TFunc
  retType:uint32;
  hasVarLenParam:bool; // Func type.
  isCFunc:bool; // Func type.
  isBoxed:bool; // Enum type.
  // TypeArguments, also for funcTy's paramTypes
  typeArgs:[uint32];
  // TypeArguments, also for structdef Ty's paramTypes
  typeLocalMemberArgs:[uint32];
  dims: uint64 = 0; // RawArray
}

table MangledNamePair {
  index: uint32; // index to the vector bytecode in Definition
  mangled: uint32; // index to the vector mangledNames in Model
}

table CodePositionPair {
  index: uint32; // index to the vector bytecode in Definition
  pos: CodePosition;
}

struct VMethod {
  method : uint32; // index to the vector mangledNames in Model
  function : uint32; // index to the vector mangledNames in Model
}

table ClassElem {
  mangledName : uint32; // index to the vector mangledNames in Model
  superClasses : [uint32]; // indexes to the vector mangledNames in Model
  vtable : [VMethod];
  finalizer: uint32 = 0;
}

table Definition {
  mangledIndex: uint32;
  numArgs: uint32;
  numLVars: uint32;
  bytecodes: [uint32];
  mangledNamesMap: [MangledNamePair];
  codePositions: [CodePositionPair];
}

table Model {
  // WORK IN PROGRESS
  packageName: string;        // package name
  allTypes: [TType];          // all saved types
  bchirTypes: [uint32];       // the bchir package types, pointers to allTypes
  mangledNames: [string];
  globalVars: [Definition];
  functions: [Definition];
  classTable: [ClassElem];
  globalInitFunc: string;
  fileNames: [string];
  strings: [string];
}

root_type Model;