/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */
class ClassA {
}

class TestB {
}

class HelloC {
}

class BarFooBar {
}

class Dog1 {
    public method(): void {
    }
}

class Dog2 {
    public helloWorld(): void {
    }

}

class Dog3 {

    public test(): void {
    }
}

class Dog4 {
    public timeFooTime(): void {
    }
}

class Cat1 {
    public method: int;
}

class Cat2 {
    public helloWorld: int;
}

class Cat3 {

    public test: int;
}

class Cat4 {

    public timeFooTime: int;
}
