class KEY(object):
    def __init__(self, internal_name, external_name):
        self.internalName = internal_name
        self.externalName = external_name


class REQUEST(object):
    def __init__(self, internal_name, external_name):
        self.internalName = internal_name
        self.externalName = external_name


class KIND(object):
    def __init__(self, internal_name, external_name):
        self.internalName = internal_name
        self.externalName = external_name


UID_KEYS = [
    KEY('VersionMajor', 'key.version_major'),
    KEY('VersionMinor', 'key.version_minor'),
    KEY('VersionPatch', 'key.version_patch'),
    KEY('Results', 'key.results'),
    KEY('Request', 'key.request'),
    KEY('Notification', 'key.notification'),
    KEY('Kind', 'key.kind'),
    KEY('AccessLevel', 'key.accessibility'),
    KEY('SetterAccessLevel', 'key.setter_accessibility'),
    KEY('Keyword', 'key.keyword'),
    KEY('Name', 'key.name'),
    KEY('USR', 'key.usr'),
    KEY('OriginalUSR', 'key.original_usr'),
    KEY('DefaultImplementationOf', 'key.default_implementation_of'),
    KEY('InterestedUSR', 'key.interested_usr'),
    KEY('GenericParams', 'key.generic_params'),
    KEY('GenericRequirements', 'key.generic_requirements'),
    KEY('DocFullAsXML', 'key.doc.full_as_xml'),
    KEY('DocComment', 'key.doc_comment'),
    KEY('Line', 'key.line'),
    KEY('Column', 'key.column'),
    KEY('ReceiverUSR', 'key.receiver_usr'),
    KEY('Receivers', 'key.receivers'),
    KEY('IsDynamic', 'key.is_dynamic'),
    KEY('IsImplicit', 'key.is_implicit'),
    KEY('FilePath', 'key.filepath'),
    KEY('ModuleInterfaceName', 'key.module_interface_name'),
    KEY('Hash', 'key.hash'),
    KEY('Severity', 'key.severity'),
    KEY('Offset', 'key.offset'),
    KEY('Length', 'key.length'),
    KEY('SourceFile', 'key.sourcefile'),
    KEY('PrimaryFile', 'key.primary_file'),
    KEY('EnableSyntaxMap', 'key.enablesyntaxmap'),
    KEY('EnableStructure', 'key.enablesubstructure'),
    KEY('ID', 'key.id'),
    KEY('Description', 'key.description'),
    KEY('TypeName', 'key.typename'),
    KEY('RuntimeName', 'key.runtime_name'),
    KEY('SelectorName', 'key.selector_name'),
    KEY('AnnotatedDecl', 'key.annotated_decl'),
    KEY('FullyAnnotatedDecl', 'key.fully_annotated_decl'),
    KEY('FullyAnnotatedGenericSignature',
        'key.fully_annotated_generic_signature'),
    KEY('DocBrief', 'key.doc.brief'),
    KEY('Context', 'key.context'),
    KEY('TypeRelation', 'key.typerelation'),
    KEY('ModuleImportDepth', 'key.moduleimportdepth'),
    KEY('NumBytesToErase', 'key.num_bytes_to_erase'),
    KEY('NotRecommended', 'key.not_recommended'),
    KEY('Declarations', 'key.declarations'),
    KEY('EnableDeclarations', 'key.enabledeclarations'),
    KEY('Annotations', 'key.annotations'),
    KEY('SemanticTokens', 'key.semantic_tokens'),
    KEY('DiagnosticStage', 'key.diagnostic_stage'),
    KEY('SyntaxMap', 'key.syntaxmap'),
    KEY('IsSystem', 'key.is_system'),
    KEY('Related', 'key.related'),
    KEY('Inherits', 'key.inherits'),
    KEY('Conforms', 'key.conforms'),
    KEY('Extends', 'key.extends'),
    KEY('Dependencies', 'key.dependencies'),
    KEY('Entities', 'key.entities'),
    KEY('NameOffset', 'key.nameoffset'),
    KEY('NameLength', 'key.namelength'),
    KEY('BodyOffset', 'key.bodyoffset'),
    KEY('BodyLength', 'key.bodylength'),
    KEY('DocOffset', 'key.docoffset'),
    KEY('DocLength', 'key.doclength'),
    KEY('IsActive', 'key.is_active'),
    KEY('IsLocal', 'key.is_local'),
    KEY('InheritedTypes', 'key.inheritedtypes'),
    KEY('Attributes', 'key.attributes'),
    KEY('Attribute', 'key.attribute'),
    KEY('Elements', 'key.elements'),
    KEY('SubStructure', 'key.substructure'),
    KEY('Ranges', 'key.ranges'),
    KEY('Fixits', 'key.fixits'),
    KEY('GeneratedBuffers', 'key.generated_buffers'),
    KEY('BufferText', 'key.buffer_text'),
    KEY('OriginalLocation', 'key.original_location'),
    KEY('Diagnostics', 'key.diagnostics'),
    KEY('EducationalNotePaths', 'key.educational_note_paths'),
    KEY('FormatOptions', 'key.editor.format.options'),
    KEY('CodeCompleteOptions', 'key.codecomplete.options'),
    KEY('TypeContextInfoOptions', 'key.typecontextinfo.options'),
    KEY('ConformingMethodListOptions', 'key.conformingmethods.options'),
    KEY('FilterRules', 'key.codecomplete.filterrules'),
    KEY('NextRequestStart', 'key.nextrequeststart'),
    KEY('Popular', 'key.popular'),
    KEY('Unpopular', 'key.unpopular'),
    KEY('Hide', 'key.hide'),
    KEY('Platform', 'key.platform'),
    KEY('IsDeprecated', 'key.is_deprecated'),
    KEY('IsUnavailable', 'key.is_unavailable'),
    KEY('IsOptional', 'key.is_optional'),
    KEY('IsAsync', 'key.is_async'),
    KEY('Message', 'key.message'),
    KEY('Introduced', 'key.introduced'),
    KEY('Deprecated', 'key.deprecated'),
    KEY('Obsoleted', 'key.obsoleted'),
    KEY('CancelBuilds', 'key.cancel_builds'),
    KEY('RemoveCache', 'key.removecache'),
    KEY('TypeUsr', 'key.typeusr'),
    KEY('ContainerTypeUsr', 'key.containertypeusr'),
    KEY('ModuleGroups', 'key.modulegroups'),
    KEY('BaseName', 'key.basename'),
    KEY('ArgNames', 'key.argnames'),
    KEY('SelectorPieces', 'key.selectorpieces'),
    KEY('NameKind', 'key.namekind'),
    KEY('LocalizationKey', 'key.localization_key'),
    KEY('IsZeroArgSelector', 'key.is_zero_arg_selector'),
    KEY('CodiraVersion', 'key.code_version'),
    KEY('Value', 'key.value'),
    KEY('EnableDiagnostics', 'key.enablediagnostics'),
    KEY('GroupName', 'key.groupname'),
    KEY('ActionName', 'key.actionname'),
    KEY('SynthesizedExtension', 'key.synthesizedextensions'),
    KEY('UsingCodiraArgs', 'key.usinglanguageargs'),
    KEY('Names', 'key.names'),
    KEY('UIDs', 'key.uids'),
    KEY('SyntacticOnly', 'key.syntactic_only'),
    KEY('ParentLoc', 'key.parent_loc'),
    KEY('IsTestCandidate', 'key.is_test_candidate'),
    KEY('Overrides', 'key.overrides'),
    KEY('AssociatedUSRs', 'key.associated_usrs'),
    KEY('ModuleName', 'key.modulename'),
    KEY('RelatedDecls', 'key.related_decls'),
    KEY('Simplified', 'key.simplified'),
    KEY('RangeContent', 'key.rangecontent'),
    KEY('CancelOnSubsequentRequest', 'key.cancel_on_subsequent_request'),
    KEY('IncludeNonEditableBaseNames', 'key.include_non_editable_base_names'),
    KEY('RenameLocations', 'key.renamelocations'),
    KEY('Locations', 'key.locations'),
    KEY('NameType', 'key.nametype'),
    KEY('NewName', 'key.newname'),
    KEY('CategorizedEdits', 'key.categorizededits'),
    KEY('CategorizedRanges', 'key.categorizedranges'),
    KEY('RangesWorthNote', 'key.rangesworthnote'),
    KEY('Edits', 'key.edits'),
    KEY('EndLine', 'key.endline'),
    KEY('EndColumn', 'key.endcolumn'),
    KEY('ArgIndex', 'key.argindex'),
    KEY('Text', 'key.text'),
    KEY('Category', 'key.category'),
    KEY('Categories', 'key.categories'),
    KEY('IsFunctionLike', 'key.is_function_like'),
    KEY('IsNonProtocolType', 'key.is_non_protocol_type'),
    KEY('RefactorActions', 'key.refactor_actions'),
    KEY('RetrieveRefactorActions', 'key.retrieve_refactor_actions'),
    KEY('SymbolGraph', 'key.symbol_graph'),
    KEY('RetrieveSymbolGraph', 'key.retrieve_symbol_graph'),
    KEY('ParentContexts', 'key.parent_contexts'),
    KEY('ReferencedSymbols', 'key.referenced_symbols'),
    KEY('IsSPI', 'key.is_spi'),
    KEY('ActionUID', 'key.actionuid'),
    KEY('ActionUnavailableReason', 'key.actionunavailablereason'),
    KEY('CompileID', 'key.compileid'),
    KEY('CompilerArgsString', 'key.compilerargs-string'),
    KEY('ImplicitMembers', 'key.implicitmembers'),
    KEY('ExpectedTypes', 'key.expectedtypes'),
    KEY('Members', 'key.members'),
    KEY('TypeBuffer', 'key.printedtypebuffer'),
    KEY('ExpressionTypeList', 'key.expression_type_list'),
    KEY('ExpressionOffset', 'key.expression_offset'),
    KEY('ExpressionLength', 'key.expression_length'),
    KEY('ExpressionType', 'key.expression_type'),
    KEY('VariableTypeList', 'key.variable_type_list'),
    KEY('VariableOffset', 'key.variable_offset'),
    KEY('VariableLength', 'key.variable_length'),
    KEY('VariableType', 'key.variable_type'),
    KEY('VariableTypeExplicit', 'key.variable_type_explicit'),
    KEY('FullyQualified', 'key.fully_qualified'),
    KEY('CanonicalizeType', 'key.canonicalize_type'),
    KEY('InternalDiagnostic', 'key.internal_diagnostic'),
    KEY('VFSName', 'key.vfs.name'),
    KEY('VFSOptions', 'key.vfs.options'),
    KEY('Files', 'key.files'),
    KEY('OptimizeForIDE', 'key.optimize_for_ide'),
    KEY('RequiredBystanders', 'key.required_bystanders'),
    KEY('ReusingASTContext', 'key.reusingastcontext'),
    KEY('CompletionMaxASTContextReuseCount',
        'key.completion_max_astcontext_reuse_count'),
    KEY('CompletionCheckDependencyInterval',
        'key.completion_check_dependency_interval'),
    KEY('AnnotatedTypename', 'key.annotated.typename'),
    KEY('CompileOperation', 'key.compile_operation'),
    KEY('EffectiveAccess', 'key.effective_access'),
    KEY('DeclarationLang', 'key.decl_lang'),
    KEY('SecondarySymbols', 'key.secondary_symbols'),
    # Before executing the actual request wait x ms. The request can be canceled
    # in this time. For cancellation testing purposes.
    KEY('SimulateLongRequest', 'key.simulate_long_request'),
    KEY('IsSynthesized', 'key.is_synthesized'),
    KEY('BufferName', 'key.buffer_name'),
    KEY('BarriersEnabled', 'key.barriers_enabled'),
    KEY('Expansions', 'key.expansions'),
    KEY('MacroRoles', 'key.macro_roles'),
    KEY('ExpandedMacroReplacements', 'key.expanded_macro_replacements'),
    KEY('IndexStorePath', 'key.index_store_path'),
    KEY('IndexUnitOutputPath', 'key.index_unit_output_path'),
    KEY('IncludeLocals', 'key.include_locals'),
    KEY('IgnoreClangModules', 'key.ignore_clang_modules'),
    KEY('IncludeSystemModules', 'key.include_system_modules'),
    KEY('IgnoreStdlib', 'key.ignore_stdlib'),
    KEY('DisableImplicitModules', 'key.disable_implicit_modules'),

    KEY('CompilerArgs', 'key.compilerargs'),
    KEY('SourceText', 'key.sourcetext'),

    # IMPORTANT: Add any new keys before CompilerArgs and SourceText.
    # Always keep CompilerArgs and SourceText as the last keys so that printing
    # a request dictionary has those as the last entries. That way, when the
    # request gets truncated by os_log in sourcekit-lsp, we see most of the
    # request. Most likely the sourcetext and the compiler args wouldn't have
    # made it into the log message completely anyway.
]


UID_REQUESTS = [
    REQUEST('ProtocolVersion', 'source.request.protocol_version'),
    REQUEST('CompilerVersion', 'source.request.compiler_version'),
    REQUEST('CrashWithExit', 'source.request.crash_exit'),
    REQUEST('Demangle', 'source.request.demangle'),
    REQUEST('MangleSimpleClass', 'source.request.mangle_simple_class'),
    REQUEST('Index', 'source.request.indexsource'),
    REQUEST('DocInfo', 'source.request.docinfo'),
    REQUEST('CodeComplete', 'source.request.codecomplete'),
    REQUEST('CodeCompleteOpen', 'source.request.codecomplete.open'),
    REQUEST('CodeCompleteClose', 'source.request.codecomplete.close'),
    REQUEST('CodeCompleteUpdate', 'source.request.codecomplete.update'),
    REQUEST('CodeCompleteCacheOnDisk',
            'source.request.codecomplete.cache.ondisk'),
    REQUEST('CodeCompleteSetPopularAPI',
            'source.request.codecomplete.setpopularapi'),
    REQUEST('CodeCompleteSetCustom', 'source.request.codecomplete.setcustom'),
    REQUEST('TypeContextInfo', 'source.request.typecontextinfo'),
    REQUEST('ConformingMethodList', 'source.request.conformingmethods'),
    REQUEST('ActiveRegions', 'source.request.activeregions'),
    REQUEST('CursorInfo', 'source.request.cursorinfo'),
    REQUEST('RangeInfo', 'source.request.rangeinfo'),
    REQUEST('RelatedIdents', 'source.request.relatedidents'),
    REQUEST('EditorOpen', 'source.request.editor.open'),
    REQUEST('EditorOpenInterface', 'source.request.editor.open.interface'),
    REQUEST('EditorOpenHeaderInterface',
            'source.request.editor.open.interface.header'),
    REQUEST('EditorOpenCodiraSourceInterface',
            'source.request.editor.open.interface.codesource'),
    REQUEST('EditorOpenCodiraTypeInterface',
            'source.request.editor.open.interface.codetype'),
    REQUEST('EditorExtractTextFromComment',
            'source.request.editor.extract.comment'),
    REQUEST('EditorClose', 'source.request.editor.close'),
    REQUEST('EditorReplaceText', 'source.request.editor.replacetext'),
    REQUEST('EditorFormatText', 'source.request.editor.formattext'),
    REQUEST('EditorExpandPlaceholder',
            'source.request.editor.expand_placeholder'),
    REQUEST('EditorFindUSR', 'source.request.editor.find_usr'),
    REQUEST('EditorFindInterfaceDoc',
            'source.request.editor.find_interface_doc'),
    REQUEST('BuildSettingsRegister', 'source.request.buildsettings.register'),
    REQUEST('ModuleGroups', 'source.request.module.groups'),
    REQUEST('NameTranslation', 'source.request.name.translation'),
    REQUEST('MarkupToXML', 'source.request.convert.markup.xml'),
    REQUEST('Statistics', 'source.request.statistics'),
    REQUEST('FindRenameRanges', 'source.request.find-syntactic-rename-ranges'),
    REQUEST('FindLocalRenameRanges',
            'source.request.find-local-rename-ranges'),
    REQUEST('SemanticRefactoring', 'source.request.semantic.refactoring'),
    REQUEST('EnableCompileNotifications',
            'source.request.enable-compile-notifications'),
    REQUEST('TestNotification', 'source.request.test_notification'),
    REQUEST('CollectExpressionType', 'source.request.expression.type'),
    REQUEST('CollectVariableType', 'source.request.variable.type'),
    REQUEST('GlobalConfiguration', 'source.request.configuration.global'),
    REQUEST('DependencyUpdated', 'source.request.dependency_updated'),
    REQUEST('Diagnostics', 'source.request.diagnostics'),
    REQUEST('SemanticTokens', 'source.request.semantic_tokens'),
    REQUEST('Compile', 'source.request.compile'),
    REQUEST('CompileClose', 'source.request.compile.close'),
    REQUEST('EnableRequestBarriers', 'source.request.enable_request_barriers'),
    REQUEST('SyntacticMacroExpansion',
            'source.request.syntactic_macro_expansion'),
    REQUEST('IndexToStore', 'source.request.index_to_store'),
]


UID_KINDS = [
    KIND('DeclFunctionFree', 'source.lang.code.decl.function.free'),
    KIND('RefFunctionFree', 'source.lang.code.ref.function.free'),
    KIND('DeclMethodInstance',
         'source.lang.code.decl.function.method.instance'),
    KIND('RefMethodInstance',
         'source.lang.code.ref.function.method.instance'),
    KIND('DeclMethodStatic', 'source.lang.code.decl.function.method.static'),
    KIND('RefMethodStatic', 'source.lang.code.ref.function.method.static'),
    KIND('DeclMethodClass', 'source.lang.code.decl.function.method.class'),
    KIND('RefMethodClass', 'source.lang.code.ref.function.method.class'),
    KIND('DeclAccessorGetter',
         'source.lang.code.decl.function.accessor.getter'),
    KIND('RefAccessorGetter',
         'source.lang.code.ref.function.accessor.getter'),
    KIND('DeclAccessorSetter',
         'source.lang.code.decl.function.accessor.setter'),
    KIND('RefAccessorSetter',
         'source.lang.code.ref.function.accessor.setter'),
    KIND('DeclAccessorWillSet',
         'source.lang.code.decl.function.accessor.willset'),
    KIND('RefAccessorWillSet',
         'source.lang.code.ref.function.accessor.willset'),
    KIND('DeclAccessorDidSet',
         'source.lang.code.decl.function.accessor.didset'),
    KIND('RefAccessorDidSet',
         'source.lang.code.ref.function.accessor.didset'),
    KIND('DeclAccessorAddress',
         'source.lang.code.decl.function.accessor.address'),
    KIND('RefAccessorAddress',
         'source.lang.code.ref.function.accessor.address'),
    KIND('DeclAccessorMutableAddress',
         'source.lang.code.decl.function.accessor.mutableaddress'),
    KIND('RefAccessorMutableAddress',
         'source.lang.code.ref.function.accessor.mutableaddress'),
    KIND('DeclAccessorRead',
         'source.lang.code.decl.function.accessor.read'),
    KIND('RefAccessorRead',
         'source.lang.code.ref.function.accessor.read'),
    KIND('DeclAccessorModify',
         'source.lang.code.decl.function.accessor.modify'),
    KIND('RefAccessorModify',
         'source.lang.code.ref.function.accessor.modify'),
    KIND('DeclAccessorInit',
         'source.lang.code.decl.function.accessor.init'),
    KIND('RefAccessorInit',
         'source.lang.code.ref.function.accessor.init'),
    KIND('DeclConstructor', 'source.lang.code.decl.function.constructor'),
    KIND('RefConstructor', 'source.lang.code.ref.function.constructor'),
    KIND('DeclDestructor', 'source.lang.code.decl.function.destructor'),
    KIND('RefDestructor', 'source.lang.code.ref.function.destructor'),
    KIND('DeclFunctionPrefixOperator',
         'source.lang.code.decl.function.operator.prefix'),
    KIND('DeclFunctionPostfixOperator',
         'source.lang.code.decl.function.operator.postfix'),
    KIND('DeclFunctionInfixOperator',
         'source.lang.code.decl.function.operator.infix'),
    KIND('RefFunctionPrefixOperator',
         'source.lang.code.ref.function.operator.prefix'),
    KIND('RefFunctionPostfixOperator',
         'source.lang.code.ref.function.operator.postfix'),
    KIND('RefFunctionInfixOperator',
         'source.lang.code.ref.function.operator.infix'),
    KIND('DeclPrecedenceGroup', 'source.lang.code.decl.precedencegroup'),
    KIND('RefPrecedenceGroup', 'source.lang.code.ref.precedencegroup'),
    KIND('DeclSubscript', 'source.lang.code.decl.function.subscript'),
    KIND('RefSubscript', 'source.lang.code.ref.function.subscript'),
    KIND('DeclVarGlobal', 'source.lang.code.decl.var.global'),
    KIND('RefVarGlobal', 'source.lang.code.ref.var.global'),
    KIND('DeclVarInstance', 'source.lang.code.decl.var.instance'),
    KIND('RefVarInstance', 'source.lang.code.ref.var.instance'),
    KIND('DeclVarStatic', 'source.lang.code.decl.var.static'),
    KIND('RefVarStatic', 'source.lang.code.ref.var.static'),
    KIND('DeclVarClass', 'source.lang.code.decl.var.class'),
    KIND('RefVarClass', 'source.lang.code.ref.var.class'),
    KIND('DeclVarLocal', 'source.lang.code.decl.var.local'),
    KIND('RefVarLocal', 'source.lang.code.ref.var.local'),
    KIND('DeclVarParam', 'source.lang.code.decl.var.parameter'),
    KIND('DeclModule', 'source.lang.code.decl.module'),
    KIND('DeclClass', 'source.lang.code.decl.class'),
    KIND('RefClass', 'source.lang.code.ref.class'),
    KIND('DeclActor', 'source.lang.code.decl.actor'),
    KIND('RefActor', 'source.lang.code.ref.actor'),
    KIND('DeclStruct', 'source.lang.code.decl.struct'),
    KIND('RefStruct', 'source.lang.code.ref.struct'),
    KIND('DeclEnum', 'source.lang.code.decl.enum'),
    KIND('RefEnum', 'source.lang.code.ref.enum'),
    KIND('DeclEnumCase', 'source.lang.code.decl.enumcase'),
    KIND('DeclEnumElement', 'source.lang.code.decl.enumelement'),
    KIND('RefEnumElement', 'source.lang.code.ref.enumelement'),
    KIND('DeclProtocol', 'source.lang.code.decl.protocol'),
    KIND('RefProtocol', 'source.lang.code.ref.protocol'),
    KIND('DeclExtension', 'source.lang.code.decl.extension'),
    KIND('DeclExtensionStruct', 'source.lang.code.decl.extension.struct'),
    KIND('DeclExtensionClass', 'source.lang.code.decl.extension.class'),
    KIND('DeclExtensionEnum', 'source.lang.code.decl.extension.enum'),
    KIND('DeclExtensionProtocol', 'source.lang.code.decl.extension.protocol'),
    KIND('DeclAssociatedType', 'source.lang.code.decl.associatedtype'),
    KIND('RefAssociatedType', 'source.lang.code.ref.associatedtype'),
    KIND('DeclOpaqueType', 'source.lang.code.decl.opaquetype'),
    KIND('RefOpaqueType', 'source.lang.code.ref.opaquetype'),
    KIND('DeclTypeAlias', 'source.lang.code.decl.typealias'),
    KIND('RefTypeAlias', 'source.lang.code.ref.typealias'),
    KIND('DeclGenericTypeParam', 'source.lang.code.decl.generic_type_param'),
    KIND('RefGenericTypeParam', 'source.lang.code.ref.generic_type_param'),
    KIND('DeclMacro', 'source.lang.code.decl.macro'),
    KIND('RefMacro', 'source.lang.code.ref.macro'),
    KIND('RefModule', 'source.lang.code.ref.module'),
    KIND('CommentTag', 'source.lang.code.commenttag'),
    KIND('StmtForEach', 'source.lang.code.stmt.foreach'),
    KIND('StmtFor', 'source.lang.code.stmt.for'),
    KIND('StmtWhile', 'source.lang.code.stmt.while'),
    KIND('StmtRepeatWhile', 'source.lang.code.stmt.repeatwhile'),
    KIND('StmtIf', 'source.lang.code.stmt.if'),
    KIND('StmtGuard', 'source.lang.code.stmt.guard'),
    KIND('StmtSwitch', 'source.lang.code.stmt.switch'),
    KIND('StmtCase', 'source.lang.code.stmt.case'),
    KIND('StmtBrace', 'source.lang.code.stmt.brace'),
    KIND('ExprCall', 'source.lang.code.expr.call'),
    KIND('ExprArg', 'source.lang.code.expr.argument'),
    KIND('ExprArray', 'source.lang.code.expr.array'),
    KIND('ExprDictionary', 'source.lang.code.expr.dictionary'),
    KIND('ExprObjectLiteral', 'source.lang.code.expr.object_literal'),
    KIND('ExprTuple', 'source.lang.code.expr.tuple'),
    KIND('ExprClosure', 'source.lang.code.expr.closure'),
    KIND('StructureElemId', 'source.lang.code.structure.elem.id'),
    KIND('StructureElemExpr', 'source.lang.code.structure.elem.expr'),
    KIND('StructureElemInitExpr',
         'source.lang.code.structure.elem.init_expr'),
    KIND('StructureElemCondExpr',
         'source.lang.code.structure.elem.condition_expr'),
    KIND('StructureElemPattern', 'source.lang.code.structure.elem.pattern'),
    KIND('StructureElemTypeRef', 'source.lang.code.structure.elem.typeref'),
    KIND('RangeSingleStatement', 'source.lang.code.range.singlestatement'),
    KIND('RangeSingleExpression', 'source.lang.code.range.singleexpression'),
    KIND('RangeSingleDeclaration',
         'source.lang.code.range.singledeclaration'),
    KIND('RangeMultiStatement', 'source.lang.code.range.multistatement'),
    KIND('RangeMultiTypeMemberDeclaration',
         'source.lang.code.range.multitypememberdeclaration'),
    KIND('RangeInvalid', 'source.lang.code.range.invalid'),
    KIND('NameObjc', 'source.lang.name.kind.objc'),
    KIND('NameCodira', 'source.lang.name.kind.code'),
    KIND('Keyword', 'source.lang.code.syntaxtype.keyword'),
    KIND('Identifier', 'source.lang.code.syntaxtype.identifier'),
    KIND('Operator', 'source.lang.code.syntaxtype.operator'),
    KIND('TypeIdentifier', 'source.lang.code.syntaxtype.typeidentifier'),
    KIND('BuildConfigKeyword',
         'source.lang.code.syntaxtype.buildconfig.keyword'),
    KIND('BuildConfigId', 'source.lang.code.syntaxtype.buildconfig.id'),
    KIND('PoundDirectiveKeyword',
         'source.lang.code.syntaxtype.pounddirective.keyword'),
    KIND('AttributeId', 'source.lang.code.syntaxtype.attribute.id'),
    KIND('AttributeBuiltin', 'source.lang.code.syntaxtype.attribute.builtin'),
    KIND('Number', 'source.lang.code.syntaxtype.number'),
    KIND('String', 'source.lang.code.syntaxtype.string'),
    KIND('StringInterpolation',
         'source.lang.code.syntaxtype.string_interpolation_anchor'),
    KIND('Comment', 'source.lang.code.syntaxtype.comment'),
    KIND('DocComment', 'source.lang.code.syntaxtype.doccomment'),
    KIND('DocCommentField', 'source.lang.code.syntaxtype.doccomment.field'),
    KIND('CommentMarker', 'source.lang.code.syntaxtype.comment.mark'),
    KIND('CommentURL', 'source.lang.code.syntaxtype.comment.url'),
    KIND('Placeholder', 'source.lang.code.syntaxtype.placeholder'),
    KIND('ObjectLiteral', 'source.lang.code.syntaxtype.objectliteral'),
    KIND('Expr', 'source.lang.code.expr'),
    KIND('Stmt', 'source.lang.code.stmt'),
    KIND('Type', 'source.lang.code.type'),
    KIND('ForEachSequence', 'source.lang.code.foreach.sequence'),
    KIND('DiagNote', 'source.diagnostic.severity.note'),
    KIND('DiagWarning', 'source.diagnostic.severity.warning'),
    KIND('DiagError', 'source.diagnostic.severity.error'),
    KIND('DiagDeprecation', 'source.diagnostic.category.deprecation'),
    KIND('DiagNoUsage', 'source.diagnostic.category.no_usage'),
    KIND('CodeCompletionEverything', 'source.codecompletion.everything'),
    KIND('CodeCompletionModule', 'source.codecompletion.module'),
    KIND('CodeCompletionKeyword', 'source.codecompletion.keyword'),
    KIND('CodeCompletionLiteral', 'source.codecompletion.literal'),
    KIND('CodeCompletionCustom', 'source.codecompletion.custom'),
    KIND('CodeCompletionIdentifier', 'source.codecompletion.identifier'),
    KIND('CodeCompletionDescription', 'source.codecompletion.description'),
    KIND('EditActive', 'source.edit.kind.active'),
    KIND('EditInactive', 'source.edit.kind.inactive'),
    KIND('EditSelector', 'source.edit.kind.selector'),
    KIND('EditString', 'source.edit.kind.string'),
    KIND('EditComment', 'source.edit.kind.comment'),
    KIND('EditMismatch', 'source.edit.kind.mismatch'),
    KIND('EditUnknown', 'source.edit.kind.unknown'),
    KIND('RenameRangeBase', 'source.refactoring.range.kind.basename'),
    KIND('RenameRangeKeywordBase',
         'source.refactoring.range.kind.keyword-basename'),
    KIND('RenameRangeParam',
         'source.refactoring.range.kind.parameter-and-whitespace'),
    KIND('RenameRangeNoncollapsibleParam',
         'source.refactoring.range.kind.noncollapsible-parameter'),
    KIND('RenameRangeDeclArgLabel',
         'source.refactoring.range.kind.decl-argument-label'),
    KIND('RenameRangeCallArgLabel',
         'source.refactoring.range.kind.call-argument-label'),
    KIND('RenameRangeCallArgColon',
         'source.refactoring.range.kind.call-argument-colon'),
    KIND('RenameRangeCallArgCombined',
         'source.refactoring.range.kind.call-argument-combined'),
    KIND('RenameRangeSelectorArgLabel',
         'source.refactoring.range.kind.selector-argument-label'),
    KIND('Definition', 'source.syntacticrename.definition'),
    KIND('Reference', 'source.syntacticrename.reference'),
    KIND('Call', 'source.syntacticrename.call'),
    KIND('Unknown', 'source.syntacticrename.unknown'),
    KIND('StatNumRequests', 'source.statistic.num-requests'),
    KIND('StatNumSemaRequests', 'source.statistic.num-semantic-requests'),
    KIND('StatInstructionCount', 'source.statistic.instruction-count'),
    KIND('Codira', 'source.lang.code'),
    KIND('ObjC', 'source.lang.objc'),
    KIND('MacroRoleExpression', 'source.lang.code.macro_role.expression'),
    KIND('MacroRoleDeclaration', 'source.lang.code.macro_role.declaration'),
    KIND('MacroRoleCodeItem', 'source.lang.code.macro_role.codeitem'),
    KIND('MacroRoleAccessor', 'source.lang.code.macro_role.accessor'),
    KIND('MacroRoleMemberAttribute', 'source.lang.code.macro_role.member_attribute'),
    KIND('MacroRoleMember', 'source.lang.code.macro_role.member'),
    KIND('MacroRolePeer', 'source.lang.code.macro_role.peer'),
    KIND('MacroRoleConformance', 'source.lang.code.macro_role.conformance'),
    KIND('MacroRoleExtension', 'source.lang.code.macro_role.extension'),
    KIND('MacroRolePreamble', 'source.lang.code.macro_role.preamble'),
    KIND('MacroRoleBody', 'source.lang.code.macro_role.body'),
]
