#===----------------------------------------------------------------------===#
#   Copyright (c) NeXTHub Corporation. All Rights Reserved.
#   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
#   Author: Tunjay Akbarli
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
#   Middletown, DE 19709, New Castle County, USA.
#===----------------------------------------------------------------------===#

add_subdirectory(ani_array)
add_subdirectory(ani_arraybuffer)
add_subdirectory(ani_async)
add_subdirectory(ani_basetype)
add_subdirectory(ani_bigint)
add_subdirectory(ani_callback)
add_subdirectory(ani_class_extends)
add_subdirectory(ani_enum)
add_subdirectory(ani_finalization)
add_subdirectory(ani_function)
add_subdirectory(ani_iface)
add_subdirectory(ani_import)
add_subdirectory(ani_inject)
add_subdirectory(ani_keep_name)
add_subdirectory(ani_maythrow)
add_subdirectory(ani_namespace)
add_subdirectory(ani_on_off)
add_subdirectory(ani_opaque)
add_subdirectory(ani_optional)
add_subdirectory(ani_overload)
add_subdirectory(ani_primitives)
add_subdirectory(ani_record)
add_subdirectory(ani_session)
add_subdirectory(ani_static)
add_subdirectory(ani_string)
add_subdirectory(ani_struct)
add_subdirectory(ani_struct_extend)
add_subdirectory(ani_test)
add_subdirectory(ani_typedarray)
add_subdirectory(ani_union)
add_subdirectory(ani_thread)
add_subdirectory(ani_bundle)
add_subdirectory(ani_bundlemanager)
add_subdirectory(ani_graphics3d)
add_subdirectory(ani_polymorphism)
add_subdirectory(ani_fixedarray)
add_subdirectory(ani_tp_cookies)
add_subdirectory(ani_tp_ui)
add_subdirectory(ani_compare)
add_subdirectory(ani_export_default)
add_subdirectory(ani_javalike_overload)
add_subdirectory(ani_new_async)
# add_subdirectory(ani_huks)
# add_subdirectory(ani_image)
