#===----------------------------------------------------------------------===#
#   Copyright (c) NeXTHub Corporation. All Rights Reserved.
#   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
#   Author: Tunjay Akbarli
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
#   Middletown, DE 19709, New Castle County, USA.
#===----------------------------------------------------------------------===#

import("//arkcompiler/runtime_core/ark_config.gni")
import("//arkcompiler/runtime_core/libabckit/abckit_config.gni")

config("guard_public_config") {
  include_dirs = [ "$ark_root/guard/include" ]
}

guard_sources = [
  "library/args_parser.cpp",
  "library/guard.cpp",
  "library/configuration/configuration.cpp",
  "library/configuration/configuration_parser.cpp",
  "library/configuration/keep_option_parser.cpp",
  "library/configuration/word_reader.cpp",
  "library/error.cpp",
  "library/name_cache/name_cache_dumper.cpp",
  "library/name_cache/name_cache_keeper.cpp",
  "library/name_cache/name_cache_parser.cpp",
  "library/name_mapping/name_mapping_manager.cpp",
  "library/name_mapping/order_name_generator.cpp",
  "library/obfuscator/element_obfuscator.cpp",
  "library/obfuscator/element_preprocessor.cpp",
  "library/obfuscator/member_descriptor_util.cpp",
  "library/obfuscator/member_linker.cpp",
  "library/obfuscator/member_obfuscator.cpp",
  "library/obfuscator/member_preprocessor.cpp",
  "library/obfuscator/name_marker.cpp",
  "library/obfuscator/obfuscator.cpp",
  "library/obfuscator/obfuscator_data_manager.cpp",
  "library/obfuscator/remove_log_obfuscator.cpp",
  "library/obfuscator/seeds_dumper.cpp",
  "library/util/file_util.cpp",
  "library/util/json_util.cpp",
  "library/util/string_util.cpp",
]

guard_include_dirs = [
  "$ark_root/guard/library",
  "$ark_root/libabckit/include",
  "$ark_root/static_core",
  "$target_gen_dir/../static_core",
]

guard_configs = [
  "$ark_root/libabckit:abckit_config",
  "$ark_root/guard/abckit_wrapper:abckit_wrapper_public_config",
  "$ark_root/static_core/libarkbase:arkbase_public_config",
]

ohos_shared_library("guard_shared") {
  sources = guard_sources

  include_dirs = guard_include_dirs

  configs = guard_configs

  public_configs = [ ":guard_public_config" ]

  deps = [
    "$ark_root/guard/abckit_wrapper:abckit_wrapper_shared",
    "$ark_root/static_core/libarkbase:libarktsbase",
  ]

  if (is_mingw || is_win) {
    output_extension = "dll"
  } else {
    output_extension = "so"
  }

  part_name = "runtime_core"
  subsystem_name = "arkcompiler"
}

ohos_static_library("guard_static") {
  sources = guard_sources

  include_dirs = guard_include_dirs

  configs = guard_configs

  public_configs = [ ":guard_public_config" ]

  deps = [ "$ark_root/guard/abckit_wrapper:abckit_wrapper_static" ]

  if (is_mingw || is_win) {
    output_extension = "lib"
  } else {
    output_extension = "a"
  }

  complete_static_lib = true

  part_name = "runtime_core"
  subsystem_name = "arkcompiler"
}

if (abckit_enable) {
  ohos_executable("guard") {
    sources = [ "guard/main.cpp" ]

    configs = [
      ":guard_public_config",
      "$ark_root/libabckit:abckit_config",
    ]

    if (is_linux) {
      libs = [ "stdc++fs" ]
    }

    if (is_mac) {
      ldflags = [
        "-Wl,-rpath,@executable_path/../lib",
        "-Wl,-rpath,@loader_path/../lib",
      ]
    }

    deps = [ ":guard_static" ]

    install_enable = false

    part_name = "runtime_core"
    subsystem_name = "arkcompiler"
  }
} else {
  group("guard") {
    deps = []
  }
}
