/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

// Autogenerated file by wrong_imm_tests.rb script -- DO NOT EDIT!

#include "libabckit/c/abckit.h"
#include "libabckit/c/metadata_core.h"
#include "libabckit/c/extensions/arkts/metadata_arkts.h"
#include "libabckit/c/extensions/js/metadata_js.h"
#include "libabckit/c/ir_core.h"

#include "helpers/helpers.h"
#include "helpers/helpers_wrong_imm.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_isaApiDynamicImp = AbckitGetIsaApiDynamicImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitWrongImmTestsIsaApiDynamicImpl0 : public ::testing::Test {};

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallrange,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallrange)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallrange, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeCreateprivateproperty,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeCreateprivateproperty)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeCreateprivateproperty,
                                    AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefinefieldbyindex,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeDefinefieldbyindex)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeDefinefieldbyindex,
                                    AbckitBitImmSize::BITSIZE_32);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefineprivateproperty,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeDefineprivateproperty)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeDefineprivateproperty,
                                    AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeDefinesendableclass,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeDefinesendableclass)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeDefinesendableclass,
                                    AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeLdsendableclass,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeLdsendableclass)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeLdsendableclass,
                                    AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeLdsendableexternalmodulevar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeLdsendableexternalmodulevar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeLdsendableexternalmodulevar,
                                    AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeLdsendablevar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeLdsendablevar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeLdsendablevar, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeNewsendableenv,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeNewsendableenv)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeNewsendableenv, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeStsendablevar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeStsendablevar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeStsendablevar, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWideldsendableexternalmodulevar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeWideldsendableexternalmodulevar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeWideldsendableexternalmodulevar,
                                    AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWideldsendablevar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeWideldsendablevar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeWideldsendablevar,
                                    AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWidenewsendableenv,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeWidenewsendableenv)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeWidenewsendableenv,
                                    AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallruntimeWidestsendablevar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallruntimeWidestsendablevar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallruntimeWidestsendablevar,
                                    AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCallthisrange,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCallthisrange)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCallthisrange, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCopyrestargs,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCopyrestargs)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCopyrestargs, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateCreateobjectwithexcludedkeys,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateCreateobjectwithexcludedkeys)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateCreateobjectwithexcludedkeys,
                                    AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefineclasswithbuffer,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateDefineclasswithbuffer)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateDefineclasswithbuffer, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinefunc,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateDefinefunc)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateDefinefunc, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateDefinemethod,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateDefinemethod)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateDefinemethod, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdlexvar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateLdlexvar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateLdlexvar, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdobjbyindex,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateLdobjbyindex)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateLdobjbyindex, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateLdprivateproperty,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateLdprivateproperty)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateLdprivateproperty, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewlexenv,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateNewlexenv)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateNewlexenv, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewlexenvwithname,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateNewlexenvwithname)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateNewlexenvwithname, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateNewobjrange,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateNewobjrange)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateNewobjrange, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSetgeneratorstate,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateSetgeneratorstate)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateSetgeneratorstate, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStlexvar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateStlexvar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateStlexvar, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStobjbyindex,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateStobjbyindex)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateStobjbyindex, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStownbyindex,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateStownbyindex)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateStownbyindex, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateStprivateproperty,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateStprivateproperty)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateStprivateproperty, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateSupercallarrowrange,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateSupercallarrowrange)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateSupercallarrowrange, AbckitBitImmSize::BITSIZE_8);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateTestin,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateTestin)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateTestin, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateThrowIfsupernotcorrectcall,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateThrowIfsupernotcorrectcall)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateThrowIfsupernotcorrectcall,
                                    AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCallrange,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideCallrange)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideCallrange, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCallthisrange,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideCallthisrange)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideCallthisrange, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCopyrestargs,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideCopyrestargs)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideCopyrestargs, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideCreateobjectwithexcludedkeys,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideCreateobjectwithexcludedkeys)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideCreateobjectwithexcludedkeys,
                                    AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdlexvar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideLdlexvar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideLdlexvar, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdobjbyindex,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideLdobjbyindex)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideLdobjbyindex, AbckitBitImmSize::BITSIZE_32);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideLdpatchvar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideLdpatchvar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideLdpatchvar, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewlexenv,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideNewlexenv)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideNewlexenv, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewlexenvwithname,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideNewlexenvwithname)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideNewlexenvwithname, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideNewobjrange,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideNewobjrange)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideNewobjrange, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStlexvar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideStlexvar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideStlexvar, AbckitBitImmSize::BITSIZE_16);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStobjbyindex,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideStobjbyindex)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideStobjbyindex, AbckitBitImmSize::BITSIZE_32);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStownbyindex,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideStownbyindex)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideStownbyindex, AbckitBitImmSize::BITSIZE_32);
}

// Test: test-kind=api, api=IsaApiDynamicImpl::iCreateWideStpatchvar,
// abc-kind=ArkTS1, category=negative-imm
TEST_F(LibAbcKitWrongImmTestsIsaApiDynamicImpl0, iCreateWideStpatchvar)
{
    helpers_wrong_imm::TestWrongImm(g_isaApiDynamicImp->iCreateWideStpatchvar, AbckitBitImmSize::BITSIZE_16);
}

}  // namespace libabckit::test
