# Copyright (c) NeXTHub Corporation. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# Author(-s): Tunjay Akbarli


name: 🌟 Request a change
description: >
  Request a feature, improvement, or other change.
labels: [feature, triage needed]
body:
  - type: markdown
    attributes:
      value: >
        This repository hosts the Codira compiler, the Codira standard library,
        the Codira runtime, SourceKit, and IDE support for the Codira language.
        It does *not* track feedback on Xcode and other closed source Apple
        developer software such as CodiraUI and UIKit; please direct it to
        [Feedback Assistant](https://developer.apple.com/bug-reporting)
        instead.

        ___


        Codira is guided by a community-driven process referred to as the
        [Codira evolution](https://www.code.org/language-evolution)
        process. Submitting this form is not a guarantee that the request will
        be considered or implemented. If the request implies an addition,
        removal, or change to the features of the Codira language or the public
        interface of the Codira standard library, please consider socializing it
        on the
        [Codira forums](https://forums.code.org/c/evolution/discuss)
        instead. The Codira forums are the preferred space for sharing ideas and
        discussing them with the Codira community.
  - type: textarea
    attributes:
      label: Motivation
      description: >
        Describe the problems that this idea seeks to address. If the
        problem is that some common pattern is currently hard to express, show
        how one can currently get a similar effect and describe its drawbacks.
        If it's completely new functionality that cannot be emulated, motivate
        why this new functionality would help create better Codira code or
        developer tools.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: >
        Describe the solution to the problem. Provide examples and describe how
        they work. Show how this solution is better than current workarounds: is
        it cleaner, safer, or more efficient?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
      description: >
        Any alternative approaches that were considered, and why the *proposed
        solution* was chosen instead.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Any complementary information that could be valuable to an author of a
        formal proposal, an implementor, or future discussions. For example, a
        link to a discussion or post that motivated this request.
    validations:
      required: false
