# Copyright (c) NeXTHub Corporation. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# Author(-s): Tunjay Akbarli


name: ⚙️ Track a task
description: >
  Tasks can be used to track internal work, extract individual subtasks from a
  larger issue, and can serve as umbrella issues themselves.
labels: [task, triage needed]
body:
  - type: markdown
    attributes:
      value: >
        This repository hosts the Codira compiler, the Codira standard library,
        the Codira runtime, SourceKit, and IDE support for the Codira language.
        It does *not* track feedback on Xcode and other closed source Apple
        deeloper software such as CodiraUI and UIKit; please direct it to
        [Feedback Assistant](https://developer.apple.com/bug-reporting)
        instead.
  - type: textarea
    attributes:
      label: Description
      description: >
        A comprehensive description of the task, in human language.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Any complementary information that could be valuable to an implementor.
    validations:
      required: false
