/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */


#ifndef MRT_RUNTIME_H
#define MRT_RUNTIME_H

// The general runtime interface/Base to provide a necessary
//  top-level access point for sub-module interaction, since
// runtime holds the instance of sub-modules (managers)
#include "Base/Log.h"

namespace MapleRuntime {
extern "C" {
// C interfaces for scan stack debug.
void MRT_FlushGCInfo();
} // extern "C"

// The manager to coordinate other runtime components

class HeapManager;
class ObjectManager;
class ExceptionManager;
class StackManager;
class SignalManager;
class LogManager;
class LoaderManager;
class ThreadManager;
class MutatorManager;
class ConcurrencyModel;
class TypeInfoManager;
#ifdef _WIN64
class WinModuleManager;
#endif

class Runtime {
public:
    // return singleton of runtime instance.
    static inline Runtime& Current()
    {
        CHECK(runtime != nullptr);
        return *runtime;
    }

    static inline Runtime* CurrentRef() { return runtime; }

    inline SignalManager& GetSignalManager()
    {
        CHECK(signalManager != nullptr);
        return *signalManager;
    }

    inline HeapManager& GetHeapManager()
    {
        CHECK(heapManager != nullptr);
        return *heapManager;
    }

    inline ObjectManager& GetObjectManager()
    {
        CHECK(objectManager != nullptr);
        return *objectManager;
    }

    inline ExceptionManager& GetExceptionManager()
    {
        CHECK(exceptionManager != nullptr);
        return *exceptionManager;
    }

    inline StackManager& GetStackManager()
    {
        CHECK(stackManager != nullptr);
        return *stackManager;
    }

    inline MutatorManager& GetMutatorManager()
    {
        CHECK(mutatorManager != nullptr);
        return *mutatorManager;
    }

    inline ConcurrencyModel& GetConcurrencyModel()
    {
        CHECK(concurrencyModel != nullptr);
        return *concurrencyModel;
    }

    inline LoaderManager& GetLoaderManager()
    {
        CHECK(loaderManager != nullptr);
        return *loaderManager;
    }

#ifdef _WIN64
    inline WinModuleManager& GetWinModuleManager()
    {
        CHECK(winModuleManager != nullptr);
        return *winModuleManager;
    }
#endif

    virtual RuntimeParam GetRuntimeParam() const = 0;
    virtual void SetGCThreshold(uint64_t threshold) = 0;

protected:
    static Runtime* runtime;

    Runtime() = default;
    virtual ~Runtime() = default;

    ConcurrencyModel* concurrencyModel = nullptr; // managed threads
    SignalManager* signalManager = nullptr;       // managed signal handling
    HeapManager* heapManager = nullptr;           // managed heap
    ObjectManager* objectManager = nullptr;       // object model
    ExceptionManager* exceptionManager = nullptr; // managed exception
    StackManager* stackManager = nullptr;         // managed stack
    LogManager* logManager = nullptr;             // log
    LoaderManager* loaderManager = nullptr;       // loader module
    MutatorManager* mutatorManager = nullptr;     // manage all mutators registered
    TypeInfoManager* typeInfoManager = nullptr;   // manage TypeInfo generated by generics
#ifdef _WIN64
    WinModuleManager* winModuleManager = nullptr; // manage windows module data
#endif
};
} // namespace MapleRuntime
#endif // MRT_RUNTIME_H
