#===----------------------------------------------------------------------===#
#   Copyright (c) NeXTHub Corporation. All Rights Reserved.
#   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
#   Author: Tunjay Akbarli
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
#   Middletown, DE 19709, New Castle County, USA.
#===----------------------------------------------------------------------===#

import("//arkcompiler/ets_runtime/common_components/tests/test_helper.gni")

module_output_path = "ets_runtime"

host_unittest_action("C_String_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "c_string_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "zlib:libz",
  ]
}

host_unittest_action("Mem_Utils_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "mem_utils_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "runtime_core:libarkassembler_static",
  ]
}

host_unittest_action("Utf_Helper_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "utf_helper_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "runtime_core:libarkassembler_static",
  ]
}

host_unittest_action("TimeUtilsTest") {
  module_out_path = module_output_path

  sources = [
    # test file
    "time_utils_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "zlib:libz",
  ]
}

group("unittest") {
  testonly = true

  # deps file
  deps = [
    ":C_String_Test",
    ":Mem_Utils_Test",
    ":Utf_Helper_Test",
    ":TimeUtilsTest",
  ]
}

group("host_unittest") {
  testonly = true

  # deps file
  deps = [
    ":C_String_TestAction",
    ":Mem_Utils_TestAction",
    ":Utf_Helper_TestAction",
    ":TimeUtilsTestAction",
  ]
}