/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

export let tuple0Object: [] = [];

export let tuple1Object: [number] = [0x55aa];

export let tuple3Object: [number, number, string] = [0xbabe, 0xcafe, `hello`];

export let tuple8Object: [number, number, string, number, number, string, number, number] = [1, 2, `three`, 4, 5, `six`, 7, 8];

export let tuple16Object: [number, number, string, number, number, string, number, number, number, number, string, number, number, string, number, number] = [
    1, 2, `three`, 4, 5, `six`, 7, 8,
    9, 10, `eleven`, 12, 13, `fourteen`, 15, 16
];
