#===----------------------------------------------------------------------===#
#   Copyright (c) NeXTHub Corporation. All Rights Reserved.
#   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
#   Author: Tunjay Akbarli
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
#   Middletown, DE 19709, New Castle County, USA.
#===----------------------------------------------------------------------===#

group("fuzztest") {
  testonly = true
  deps = []

  deps += [
    "agent:fuzztest",
    "backend:fuzztest",
    "base:fuzztest",
    "connectserversendmessage_fuzzer:fuzztest",
    "dispatcher:fuzztest",
    "dispatchprotocolmessage_fuzzer:fuzztest",
    "initializedebugger_fuzzer:fuzztest",
    "protocolhandler_fuzzer:fuzztest",
    "protocolhandlercreateerrorreply_fuzzer:fuzztest",
    "protocolhandlerdispatch_fuzzer:fuzztest",
    "protocolhandlerget_fuzzer:fuzztest",
    "protocolhandlernotif_fuzzer:fuzztest",
    "protocolhandlerprocess_fuzzer:fuzztest",
    "protocolhandlerresponse_fuzzer:fuzztest",
    "protocolhandlerrun_fuzzer:fuzztest",
    "protocolhandlersendreply_fuzzer:fuzztest",
    "pttypesbreakpointparseid_fuzzer:fuzztest",
    "pttypesbreakpointtostring_fuzzer:fuzztest",
    "pttypesexceptiondetailscolumn_fuzzer:fuzztest",
    "pttypesexceptiondetailscreate_fuzzer:fuzztest",
    "pttypesexceptiondetailsexceptionid_fuzzer:fuzztest",
    "pttypesexceptiondetailsexecutioncontextid_fuzzer:fuzztest",
    "pttypesexceptiondetailsline_fuzzer:fuzztest",
    "pttypesexceptiondetailsscriptid_fuzzer:fuzztest",
    "pttypesexceptiondetailstext_fuzzer:fuzztest",
    "pttypesexceptiondetailsurl_fuzzer:fuzztest",
    "pttypesinternalpropertydespcreate_fuzzer:fuzztest",
    "pttypesinternalpropertydespname_fuzzer:fuzztest",
    "pttypesobjectremoteobject_fuzzer:fuzztest",
    "pttypesprimitiveremoteobject_fuzzer:fuzztest",
    "pttypesprivatepropertydespcreate_fuzzer:fuzztest",
    "pttypesprivatepropertydespname_fuzzer:fuzztest",
    "pttypesremoteobjectdescription_fuzzer:fuzztest",
    "pttypesremoteobjectgetclassname_fuzzer:fuzztest",
    "pttypesremoteobjectgetsubtype_fuzzer:fuzztest",
    "pttypesremoteobjectgettype_fuzzer:fuzztest",
    "pttypesremoteobjectgetvalue_fuzzer:fuzztest",
    "pttypesremoteobjectobjectid_fuzzer:fuzztest",
    "pttypesremoteobjectunserializablevalue_fuzzer:fuzztest",
    "pttypesstringremoteobject_fuzzer:fuzztest",
    "pttypessymbolremoteobject_fuzzer:fuzztest",
  ]
}
