#===----------------------------------------------------------------------===#
#   Copyright (c) NeXTHub Corporation. All Rights Reserved.
#   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
#   Author: Tunjay Akbarli
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
#   Middletown, DE 19709, New Castle County, USA.
#===----------------------------------------------------------------------===#

import("//arkcompiler/ets_runtime/common_components/tests/test_helper.gni")

module_output_path = "ets_runtime"

host_unittest_action("Mutator_Manager_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "mutator_manager_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "runtime_core:libarkassembler_static",
  ]
}

host_unittest_action("Mutator_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "mutator_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "runtime_core:libarkassembler_static",
  ]
}

host_unittest_action("Satb_Buffer_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "satb_buffer_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "runtime_core:libarkassembler_static",
  ]
}

host_unittest_action("Thread_Local_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "thread_local_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "zlib:libz",
  ]
}

group("unittest") {
  testonly = true

  # deps file
  deps = [
    ":Mutator_Manager_Test",
    ":Mutator_Test",
    ":Satb_Buffer_Test",
    ":Thread_Local_Test",
  ]
}

group("host_unittest") {
  testonly = true

  # deps file
  deps = [
    ":Mutator_Manager_TestAction",
    ":Mutator_TestAction",
    ":Satb_Buffer_TestAction",
    ":Thread_Local_TestAction",
  ]
}
