#===----------------------------------------------------------------------===#
#   Copyright (c) NeXTHub Corporation. All Rights Reserved.
#   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
#   Author: Tunjay Akbarli
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
#   Middletown, DE 19709, New Castle County, USA.
#===----------------------------------------------------------------------===#

group("fuzztest") {
  testonly = true

  deps = [
    "aniarrayget_fuzzer:fuzztest",
    "aniarrayset_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynameboolean_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamebooleana_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamebyte_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamebytea_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamechar_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamechara_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamedouble_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamedoublea_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamefloat_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamefloata_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynameint_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynameinta_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamelong_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamelonga_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynameref_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamerefa_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynameshort_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynameshorta_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamevoid_fuzzer:fuzztest",
    "aniclasscallstaticmethodbynamevoida_fuzzer:fuzztest",
    "aniclassfindfield_fuzzer:fuzztest",
    "aniclassfindgetter_fuzzer:fuzztest",
    "aniclassfindindexablegetter_fuzzer:fuzztest",
    "aniclassfindindexablesetter_fuzzer:fuzztest",
    "aniclassfindmethod_fuzzer:fuzztest",
    "aniclassfindsetter_fuzzer:fuzztest",
    "aniclassfindstaticfield_fuzzer:fuzztest",
    "aniclassfindstaticmethod_fuzzer:fuzztest",
    "aniclassgetstaticfieldbynameboolean_fuzzer:fuzztest",
    "aniclassgetstaticfieldbynamebyte_fuzzer:fuzztest",
    "aniclassgetstaticfieldbynamechar_fuzzer:fuzztest",
    "aniclassgetstaticfieldbynamedouble_fuzzer:fuzztest",
    "aniclassgetstaticfieldbynamefloat_fuzzer:fuzztest",
    "aniclassgetstaticfieldbynameint_fuzzer:fuzztest",
    "aniclassgetstaticfieldbynamelong_fuzzer:fuzztest",
    "aniclassgetstaticfieldbynameref_fuzzer:fuzztest",
    "aniclassgetstaticfieldbynameshort_fuzzer:fuzztest",
    "aniclasssetstaticfieldbynameboolean_fuzzer:fuzztest",
    "aniclasssetstaticfieldbynamebyte_fuzzer:fuzztest",
    "aniclasssetstaticfieldbynamechar_fuzzer:fuzztest",
    "aniclasssetstaticfieldbynamedouble_fuzzer:fuzztest",
    "aniclasssetstaticfieldbynamefloat_fuzzer:fuzztest",
    "aniclasssetstaticfieldbynameint_fuzzer:fuzztest",
    "aniclasssetstaticfieldbynamelong_fuzzer:fuzztest",
    "aniclasssetstaticfieldbynameref_fuzzer:fuzztest",
    "aniclasssetstaticfieldbynameshort_fuzzer:fuzztest",
    "anicreatearraybuffer_fuzzer:fuzztest",
    "anienumgetitembyindex_fuzzer:fuzztest",
    "anienumgetitembyname_fuzzer:fuzztest",
    "anifindclass_fuzzer:fuzztest",
    "anifindenum_fuzzer:fuzztest",
    "anifindmodule_fuzzer:fuzztest",
    "anifindnamespace_fuzzer:fuzztest",
    "animodulefindclass_fuzzer:fuzztest",
    "animodulefindenum_fuzzer:fuzztest",
    "animodulefindfunction_fuzzer:fuzztest",
    "animodulefindnamespace_fuzzer:fuzztest",
    "animodulefindvariable_fuzzer:fuzztest",
    "aninamespacefindclass_fuzzer:fuzztest",
    "aninamespacefindenum_fuzzer:fuzztest",
    "aninamespacefindfunction_fuzzer:fuzztest",
    "aninamespacefindnamespace_fuzzer:fuzztest",
    "aninamespacefindvariable_fuzzer:fuzztest",
    "aniobjectcallmethodbynameboolean_fuzzer:fuzztest",
    "aniobjectcallmethodbynamebyte_fuzzer:fuzztest",
    "aniobjectcallmethodbynamechar_fuzzer:fuzztest",
    "aniobjectcallmethodbynamedouble_fuzzer:fuzztest",
    "aniobjectcallmethodbynamefloat_fuzzer:fuzztest",
    "aniobjectcallmethodbynameint_fuzzer:fuzztest",
    "aniobjectcallmethodbynamelong_fuzzer:fuzztest",
    "aniobjectcallmethodbynameref_fuzzer:fuzztest",
    "aniobjectcallmethodbynameshort_fuzzer:fuzztest",
    "aniobjectcallmethodbynamevoid_fuzzer:fuzztest",
    "aniobjectsetpropertybynameboolean_fuzzer:fuzztest",
    "aniobjectsetpropertybynamebyte_fuzzer:fuzztest",
    "aniobjectsetpropertybynamechar_fuzzer:fuzztest",
    "aniobjectsetpropertybynamedouble_fuzzer:fuzztest",
    "aniobjectsetpropertybynamefloat_fuzzer:fuzztest",
    "aniobjectsetpropertybynameint_fuzzer:fuzztest",
    "aniobjectsetpropertybynamelong_fuzzer:fuzztest",
    "aniobjectsetpropertybynameref_fuzzer:fuzztest",
    "aniobjectsetpropertybynameshort_fuzzer:fuzztest",
    "aniobjgetfieldbynameboolean_fuzzer:fuzztest",
    "aniobjgetfieldbynamebyte_fuzzer:fuzztest",
    "aniobjgetfieldbynamechar_fuzzer:fuzztest",
    "aniobjgetfieldbynamedouble_fuzzer:fuzztest",
    "aniobjgetfieldbynamefloat_fuzzer:fuzztest",
    "aniobjgetfieldbynameint_fuzzer:fuzztest",
    "aniobjgetfieldbynamelong_fuzzer:fuzztest",
    "aniobjgetfieldbynameref_fuzzer:fuzztest",
    "aniobjgetfieldbynameshort_fuzzer:fuzztest",
    "aniobjgetpropertybynameboolean_fuzzer:fuzztest",
    "aniobjgetpropertybynamebyte_fuzzer:fuzztest",
    "aniobjgetpropertybynamechar_fuzzer:fuzztest",
    "aniobjgetpropertybynamedouble_fuzzer:fuzztest",
    "aniobjgetpropertybynamefloat_fuzzer:fuzztest",
    "aniobjgetpropertybynameint_fuzzer:fuzztest",
    "aniobjgetpropertybynamelong_fuzzer:fuzztest",
    "aniobjgetpropertybynameref_fuzzer:fuzztest",
    "aniobjgetpropertybynameshort_fuzzer:fuzztest",
    "aniobjsetfieldbynameboolean_fuzzer:fuzztest",
    "aniobjsetfieldbynamebyte_fuzzer:fuzztest",
    "aniobjsetfieldbynamechar_fuzzer:fuzztest",
    "aniobjsetfieldbynamedouble_fuzzer:fuzztest",
    "aniobjsetfieldbynamefloat_fuzzer:fuzztest",
    "aniobjsetfieldbynameint_fuzzer:fuzztest",
    "aniobjsetfieldbynamelong_fuzzer:fuzztest",
    "aniobjsetfieldbynameref_fuzzer:fuzztest",
    "aniobjsetfieldbynameshort_fuzzer:fuzztest",
    "anistringnewutf16_fuzzer:fuzztest",
    "anistringnewutf8_fuzzer:fuzztest",
    "anituplevaluegetitemboolean_fuzzer:fuzztest",
    "anituplevaluegetitembyte_fuzzer:fuzztest",
    "anituplevaluegetitemchar_fuzzer:fuzztest",
    "anituplevaluegetitemdouble_fuzzer:fuzztest",
    "anituplevaluegetitemfloat_fuzzer:fuzztest",
    "anituplevaluegetitemint_fuzzer:fuzztest",
    "anituplevaluegetitemlong_fuzzer:fuzztest",
    "anituplevaluegetitemshort_fuzzer:fuzztest",
    "anituplevaluesetitemboolean_fuzzer:fuzztest",
    "anituplevaluesetitembyte_fuzzer:fuzztest",
    "anituplevaluesetitemchar_fuzzer:fuzztest",
    "anituplevaluesetitemdouble_fuzzer:fuzztest",
    "anituplevaluesetitemfloat_fuzzer:fuzztest",
    "anituplevaluesetitemint_fuzzer:fuzztest",
    "anituplevaluesetitemlong_fuzzer:fuzztest",
    "anituplevaluesetitemshort_fuzzer:fuzztest",
  ]
}
