/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */
export let arr = [1, 2, 3]

export let w = new BigInt(123)

export let w1 = new Boolean(true)

export let w2 = new String("")

export let w3 = new Number(123)

export let w4 = new Byte()

export let d2 = new Date()

export const a: number = 1
export const b: byte = 1
export const c: short = 1
export const d: int = 1
export const e: long = 1
export const f: float = 1
export const g: double = 1
export const h: char = c'1'
export const i: boolean = true
export const j: string = "1"
export const k: bigint = 1n

export const a1: Number = new Number()
export const b1: Byte = new Byte()
export const c1: Short = new Short()
export const d1: Int = new Int()
export const e1: Long = new Long()
export const f1: Float = new Float()
export const g1: Double = new Double()
export const h1: Char = new Char()
export const i1: Boolean = new Boolean()
export const j1: String = new String()
export const k1: BigInt = new BigInt()

export let s : string = "Hi"

export type Greeting = "Hello"
export let a2: "Hello" = "Hello"
export let b2: Greeting = "Hello"

export let a3: Record<string, string>;
