'use static'
/*
 * Copyright (c) 2022-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export declare const bin: number, binBig: bigint;
export declare const oct: number, octBig: bigint;
export declare const hex: number, hexBig: bigint;
export declare const dec: number, decBig: bigint;
export declare const largeBin: bigint;
export declare const largeOct: bigint;
export declare const largeDec: bigint;
export declare const largeHex: bigint;
export declare const separatedBin: bigint;
export declare const separatedOct: bigint;
export declare const separatedDec: bigint;
export declare const separatedHex: bigint;
export declare const zero: bigint;
export declare const oneBit: bigint;
export declare const twoBit: bigint;
export declare const threeBit: bigint;
export declare const neg: bigint;
export declare const negHex: bigint;
export declare let threeBitLet: bigint;
export declare const negZero: bigint;
export declare const baseChange: bigint;
export declare const leadingZeros: bigint;
export declare let bigint_v: bigint;
export declare const baseChange_v: bigint;
export declare let zero_v: bigint;
export declare let oneBit_v: bigint;
export declare let twoBit_v: bigint;
export declare let threeBit_v: bigint;
