'use static'
/*
 * Copyright (c) 2022-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export declare let x: Any;
export declare let a: Any;
export declare let person: Any;
export type Point = Any;
export declare let myPoint: Point;
export declare function printPerson(person: Any): void;
export declare let newPerson: Any;
export type Config = Any;
export declare let config: Config;
export type Calculator = Any;
export declare let myCalculator: Calculator;
export type User = Any;
export declare let user: User;
