#===----------------------------------------------------------------------===#
#   Copyright (c) NeXTHub Corporation. All Rights Reserved.
#   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
#   Author: Tunjay Akbarli
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
#   Middletown, DE 19709, New Castle County, USA.
#===----------------------------------------------------------------------===#

import("//arkcompiler/ets_runtime/common_components/tests/test_helper.gni")

module_output_path = "ets_runtime"

host_unittest_action("Copy_Barrier_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "copy_barrier_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "zlib:libz",
  ]
}

host_unittest_action("Enum_Barrier_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "enum_barrier_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "zlib:libz",
  ]
}

host_unittest_action("Idle_Barrier_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "idle_barrier_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "zlib:libz",
  ]
}

host_unittest_action("Post_Marking_Barrier_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "post_marking_barrier_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "zlib:libz",
  ]
}

host_unittest_action("Preforward_Barrier_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "preforward_barrier_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "zlib:libz",
  ]
}

host_unittest_action("Remark_Barrier_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "remark_barrier_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "zlib:libz",
  ]
}

host_unittest_action("Marking_Barrier_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "marking_barrier_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "zlib:libz",
  ]
}

host_unittest_action("Ark_Collector_Test") {
  module_out_path = module_output_path

  sources = [
    # test file
    "ark_collector_test.cpp",
  ]

  configs = [
    "//arkcompiler/ets_runtime/common_components:common_components_test_config",
    "//arkcompiler/ets_runtime:icu_path_test_config",
  ]

  deps = [ "//arkcompiler/ets_runtime/common_components:libark_common_components_test" ]

  # hiviewdfx libraries
  external_deps = [
    "bounds_checking_function:libsec_shared",
    "icu:shared_icui18n",
    "icu:shared_icuuc",
    "zlib:libz",
  ]
}

group("unittest") {
  testonly = true

  # deps file
  deps = [
    ":Ark_Collector_Test",
    ":Copy_Barrier_Test",
    ":Enum_Barrier_Test",
    ":Idle_Barrier_Test",
    ":Post_Marking_Barrier_Test",
    ":Preforward_Barrier_Test",
    ":Remark_Barrier_Test",
    ":Marking_Barrier_Test",
  ]
}

group("host_unittest") {
  testonly = true

  # deps file
  deps = [
    ":Ark_Collector_TestAction",
    ":Copy_Barrier_TestAction",
    ":Enum_Barrier_TestAction",
    ":Idle_Barrier_TestAction",
    ":Post_Marking_Barrier_TestAction",
    ":Preforward_Barrier_TestAction",
    ":Remark_Barrier_TestAction",
    ":Marking_Barrier_TestAction",
  ]
}