/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

/**
 * @file
 *
 * This file declares the codenative backend class.
 */

#ifndef CODIRA_DRIVER_BACKEND_CODENATIVE_H
#define CODIRA_DRIVER_BACKEND_CODENATIVE_H

#include "Codira/Driver/Backend/Backend.h"
#include "Codira/Driver/DriverOptions.h"
#include "Codira/Option/Option.h"

namespace Codira {
/**
 * CODENATIVEBackend generates three different kind of tools representing three different compiling stages.
 * The first stage is 'opt', which does some preprocessing on bitcode and outputs intermediate bitcode files.
 * The second stage is 'llc', which compiles bitcode into object files.
 * The final stage is 'ld', which links object files together and outputs an executable or a dynamic library.
 * For each input bitcode file, an 'opt' and a 'llc' tool will be generated.
 * Only one 'ld' linker will be used to create an executable file from all the object files (including those
 * given as input).
 */
class CODENATIVEBackend : public Backend {
public:
    /**
     * @brief The constructor of class CODENATIVEBackend.
     *
     * @param job The compilation job.
     * @param driverOptions The data structure is obtained through parsing the compilation options.
     * @param driver It is the object that triggers the compiler's compilation process.
     * @return CODENATIVEBackend The instance of CODENATIVEBackend.
     */
    CODENATIVEBackend(Job& job, const DriverOptions& driverOptions, const Driver& driver)
        : Backend(job, driverOptions, driver){};

    /**
     * @brief The destructor of class CODENATIVEBackend.
     */
    ~CODENATIVEBackend() = default;

protected:
    bool GenerateToolChain() override;
    /**
     * @brief Scan where 'opt', 'llc' and 'ld' are and get their paths.
     */
    bool PrepareDependencyPath() override;

    bool ProcessGeneration() override;

private:
    static const std::string tempFolder;

    std::string optPath;
    std::string llcPath;

    /**
     * @brief Create an instance of a codenative base tool.
     */
    std::unique_ptr<Tool> GenerateCODENativeBaseTool(const std::string& toolPath);

    std::vector<TempFileInfo> GetFrontendOutputs();

    void GenerateCacheCopyTool(const std::vector<TempFileInfo>& files, const std::string& extension);

    /**
     * @brief This function generates 'opt' tools. For each .bc input file, an 'opt' tool is generated.
     * The output is a list of filenames, which are output files of 'opt' tools.
     * We name it PreprocessTool here because the codenative backend not only does optimize (what 'opt' stands for),
     * but also does some important bitcode transformation (e.g. intrinsic functions) that 'llc' requires.
     */
    std::vector<TempFileInfo> GeneratePreprocessTools(const std::vector<TempFileInfo>& bitCodeFiles);

    void PreprocessOfNewPassManager(Tool& tool);
    bool ProcessGenerationOfNormalCompile(const std::vector<TempFileInfo>& bitCodeFiles);
    bool ProcessGenerationOfIncrementalNoChangeCompile(const std::vector<TempFileInfo>& bitCodeFiles);

    /**
     * @brief This function generates 'llc' tools. For each .opt.bc input file (which is output file from 'opt' tools)
     * a 'llc' tool is generated. The return is a list of files generated by 'llc' tools.
     */
    std::vector<TempFileInfo> GenerateCompileTool(
        const std::vector<TempFileInfo>& bitCodeFiles, bool emitAssembly = false);
};
} // namespace Codira

#endif // CODIRA_DRIVER_BACKEND_CODENATIVE_H
