/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

/**
 * @file
 *
 * This file declares the IncrementalCompilerInstance, which performs the incremental compile flow.
 */

#ifndef CODIRA_FRONTEND_INCREMENTALCOMPILERINSTANCE_H
#define CODIRA_FRONTEND_INCREMENTALCOMPILERINSTANCE_H

#include "Codira/FrontendTool/DefaultCompilerInstance.h"
#include "Codira/IncrementalCompilation/CachedMangleMap.h"
#include "Codira/IncrementalCompilation/IncrementalScopeAnalysis.h"
#include "Codira/IncrementalCompilation/IncrementalCompilationLogger.h"
#include "Codira/Parse/ASTHasher.h"

namespace Codira {

class IncrementalCompilerInstance : public DefaultCompilerInstance {
public:
    IncrementalCompilerInstance(CompilerInvocation& invocation, DiagnosticEngine& diag)
        : DefaultCompilerInstance(invocation, diag)
    {
    }
    ~IncrementalCompilerInstance() override;

    bool InitCompilerInstance() override;

    bool PerformIncrementalScopeAnalysis() override;
    bool PerformSema() override;
    bool PerformOverflowStrategy() override;
    bool PerformDesugarAfterSema() override;
    bool PerformGenericInstantiation() override;
    bool PerformMangling() override;
    bool PerformCHIRCompilation() override;
    bool PerformCodeGen() override;
    virtual bool PerformCodeoAndBchirSaving() override;

    CachedMangleMap cacheMangles;
    // Store the struct types who's layout has been changed and needs to be regenerated its IR.
    // NOTE: since class layout is generated in separate step, we don not need to collect them.
    //       And enum types have fixed layout for non-class or same as class type generation, it also can be ignored.
    std::unordered_set<Ptr<const AST::StructTy>> changedTypes;

private:
    std::unordered_set<Ptr<AST::Decl>> declsToBeReCompiled;
    // stored mangled name before sema, generated by ASTDiff
    std::list<std::string> rawIncrRemovedDecls;

    void SaveCompilationResult(Codira::IncreResult&& result);
    void LoadCachedCodegenResult() const;
    void UpdateCachedInfo() override;
    void UpdateCHIROptEffectMap();
};
} // namespace Codira

#endif // CODIRA_FRONTEND_INCREMENTALCOMPILERINSTANCE_H
