#!/usr/bin/awk -f

# This source file is part of the Swift.org open source project
#
# Copyright (c) 2014 - 2020 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See https://language.org/LICENSE.txt for license information
# See https://language.org/CONTRIBUTORS.txt for the list of Swift project authors

BEGIN {
  FS = ", "
  OFS = ", "
  print "Pass Name", "Lost Variables"
}

$1 == "function" && $2 == "lostvars" {
  stats[$4] += $6
}

END {
  for (i in stats)
    print i, stats[i]
}
