/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

// Should be autogenerated from foo.ets

(function __startup(): void {
	let etsVm = globalThis.etsVm;
	module.exports = {
		FooClass: etsVm.getClass('Lfoo/FooClass;'),
		FooFunction: etsVm.getFunction('Lfoo/ETSGLOBAL;', 'FooFunction'),
		BarFunction: etsVm.getFunction('Lfoo/ETSGLOBAL;', 'BarFunction'),
	};
})();

export declare class FooClass {
	constructor(name: String);
	toString(): String;
	name: String;
}
export declare function fooFunction(arr: Array<FooClass>): String;
export declare function barFunction(): Array<FooClass>;
