//===--- PrintAsClang.cpp - Emit a header file for a Codira AST ------------===//
//
// Copyright (c) NeXTHub Corporation. All rights reserved.
// DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// version 2 for more details (a copy is included in the LICENSE file that
// accompanied this code).
//
// Author(-s): Tunjay Akbarli
//

//===----------------------------------------------------------------------===//

#include "language/PrintAsClang/PrintAsClang.h"

#include "ClangSyntaxPrinter.h"
#include "ModuleContentsWriter.h"
#include "CodiraToClangInteropContext.h"

#include "language/AST/ASTContext.h"
#include "language/AST/Module.h"
#include "language/AST/PrettyStackTrace.h"
#include "language/Basic/Assertions.h"
#include "language/Basic/Version.h"
#include "language/ClangImporter/ClangImporter.h"
#include "language/Frontend/FrontendOptions.h"

#include "clang/Basic/FileManager.h"
#include "clang/Basic/Module.h"
#include "clang/Lex/HeaderSearch.h"

#include "toolchain/Support/FormatVariadic.h"
#include "toolchain/Support/Path.h"
#include "toolchain/Support/raw_ostream.h"

using namespace language;

static void emitCxxConditional(raw_ostream &out,
                               toolchain::function_ref<void()> cxxCase,
                               toolchain::function_ref<void()> cCase = {}) {
  out << "#if defined(__cplusplus)\n";
  cxxCase();
  if (cCase) {
    out << "#else\n";
    cCase();
  }
  out << "#endif\n";
}

static void emitObjCConditional(raw_ostream &out,
                                toolchain::function_ref<void()> objcCase,
                                toolchain::function_ref<void()> nonObjCCase = {}) {
  out << "#if defined(__OBJC__)\n";
  objcCase();
  if (nonObjCCase) {
    out << "#else\n";
    nonObjCCase();
  }
  out << "#endif\n";
}

static void emitExternC(raw_ostream &out,
                        toolchain::function_ref<void()> cCase) {
  emitCxxConditional(out, [&] {
    out << "extern \"C\" {\n";
  });
  cCase();
  emitCxxConditional(out, [&] {
    out << "} // extern \"C\"\n";
  });
}

static void writePtrauthPrologue(raw_ostream &os, ASTContext &ctx) {
  emitCxxConditional(os, [&]() {
    ClangSyntaxPrinter(ctx, os).printIgnoredDiagnosticBlock(
        "non-modular-include-in-framework-module", [&] {
          os << "#if defined(__arm64e__) && __has_include(<ptrauth.h>)\n";
          os << "# include <ptrauth.h>\n";
          os << "#else\n";
          ClangSyntaxPrinter(ctx, os).printIgnoredDiagnosticBlock(
              "reserved-macro-identifier", [&]() {
                os << "# ifndef "
                      "__ptrauth_language_value_witness_function_pointer\n";
                os << "#  define "
                      "__ptrauth_language_value_witness_function_pointer(x)\n";
                os << "# endif\n";
                os << "# ifndef __ptrauth_language_class_method_pointer\n";
                os << "#  define __ptrauth_language_class_method_pointer(x)\n";
                os << "# endif\n";
              });
          os << "#endif\n";
        });
  });
}

static void writePrologue(raw_ostream &out, ASTContext &ctx,
                          StringRef macroGuard) {

  out << "// Generated by "
      << version::getCodiraFullVersion(ctx.LangOpts.EffectiveLanguageVersion)
      << "\n"
      // Guard against recursive definition.
      << "#ifndef " << macroGuard << "\n"
      << "#define " << macroGuard
      << "\n"
         "#pragma clang diagnostic push\n"
         "#pragma clang diagnostic ignored \"-Wgcc-compat\"\n"
         "\n"
         "#if !defined(__has_include)\n"
         "# define __has_include(x) 0\n"
         "#endif\n"
         "#if !defined(__has_attribute)\n"
         "# define __has_attribute(x) 0\n"
         "#endif\n"
         "#if !defined(__has_feature)\n"
         "# define __has_feature(x) 0\n"
         "#endif\n"
         "#if !defined(__has_warning)\n"
         "# define __has_warning(x) 0\n"
         "#endif\n"
         "\n"
         "#if __has_include(<language/objc-prologue.h>)\n"
         "# include <language/objc-prologue.h>\n"
         "#endif\n"
         "\n"
         "#pragma clang diagnostic ignored \"-Wauto-import\"\n";
  emitObjCConditional(out,
                      [&] { out << "#include <Foundation/Foundation.h>\n"; });
  emitCxxConditional(
      out,
      [&] {
        out << "#include <cstdint>\n"
               "#include <cstddef>\n"
               "#include <cstdbool>\n"
               "#include <cstring>\n";
        out << "#include <stdlib.h>\n";
        out << "#include <new>\n";
        out << "#include <type_traits>\n";
      },
      [&] {
        out << "#include <stdint.h>\n"
               "#include <stddef.h>\n"
               "#include <stdbool.h>\n"
               "#include <string.h>\n";
      });
  writePtrauthPrologue(out, ctx);
  out << "\n"
         "#if !defined(LANGUAGE_TYPEDEFS)\n"
         "# define LANGUAGE_TYPEDEFS 1\n"
         "# if __has_include(<uchar.h>)\n"
         "#  include <uchar.h>\n"
         "# elif !defined(__cplusplus)\n"
         "typedef unsigned char char8_t;\n"
         "typedef uint_least16_t char16_t;\n"
         "typedef uint_least32_t char32_t;\n"
         "# endif\n"
#define MAP_SIMD_TYPE(C_TYPE, SCALAR_TYPE, _) \
         "typedef " #SCALAR_TYPE " language_" #C_TYPE "2"       \
         "  __attribute__((__ext_vector_type__(2)));\n" \
         "typedef " #SCALAR_TYPE " language_" #C_TYPE "3"       \
         "  __attribute__((__ext_vector_type__(3)));\n" \
         "typedef " #SCALAR_TYPE " language_" #C_TYPE "4"       \
         "  __attribute__((__ext_vector_type__(4)));\n"
#include "language/ClangImporter/SIMDMappedTypes.def"
         "#endif\n"
         "\n";

#define CLANG_MACRO_BODY(NAME, BODY) \
  out << "#if !defined(" NAME ")\n" \
         BODY "\n" \
         "#endif\n";

#define CLANG_MACRO(NAME, ARGS, VALUE) CLANG_MACRO_BODY(NAME, "# define " NAME ARGS " " VALUE)

#define CLANG_MACRO_ALTERNATIVE(NAME, ARGS, CONDITION, VALUE, ALTERNATIVE) CLANG_MACRO_BODY(NAME, \
  "# if " CONDITION "\n" \
  "#  define " NAME ARGS " " VALUE "\n" \
  "# else\n" \
  "#  define " NAME ARGS " " ALTERNATIVE "\n" \
  "# endif")

#define CLANG_MACRO_OBJC(NAME, ARGS, VALUE) \
  out << "#if defined(__OBJC__)\n" \
         "#if !defined(" NAME ")\n" \
         "# define " NAME ARGS " " VALUE "\n" \
         "#endif\n" \
         "#endif\n";

#define CLANG_MACRO_CXX(NAME, ARGS, VALUE, ALTERNATIVE) \
  out << "#if defined(__cplusplus)\n" \
         "# define " NAME ARGS " " VALUE "\n" \
         "#else\n" \
         "# define " NAME ARGS " " ALTERNATIVE "\n" \
         "#endif\n";

#define CLANG_MACRO_CXX_BODY(NAME, BODY) \
  out << "#if defined(__cplusplus)\n" \
         BODY "\n" \
         "#endif\n";

#include "language/PrintAsClang/ClangMacros.def"

  // LANGUAGE_IMPORT_STDLIB_SYMBOL's expansion can't be calculated in the
  // preprocessor, so write its definition here
  auto emitMacro = [&](StringRef name, StringRef value = "") {
    out << "#if !defined(" << name << ")\n";
    out << "# define " << name << " " << value << "\n";
    out << "#endif\n";
  };
  if (ctx.getStdlibModule()->isStaticLibrary()) {
    emitMacro("LANGUAGE_IMPORT_STDLIB_SYMBOL");
  } else {
    out << "#if defined(_WIN32)\n";
    emitMacro("LANGUAGE_IMPORT_STDLIB_SYMBOL", "__declspec(dllimport)");
    out << "#else\n";
    emitMacro("LANGUAGE_IMPORT_STDLIB_SYMBOL");
    out << "#endif\n";
  }

  static_assert(LANGUAGE_MAX_IMPORTED_SIMD_ELEMENTS == 4,
              "need to add SIMD typedefs here if max elements is increased");

  if (ctx.LangOpts.hasFeature(Feature::CDecl)) {
    // For C compilers which don’t support nullability attributes, ignore them;
    // for ones which do, suppress warnings about them being an extension.
    out << "#if !__has_feature(nullability)\n"
           "# define _Nonnull\n"
           "# define _Nullable\n"
           "# define _Null_unspecified\n"
           "#elif !defined(__OBJC__)\n"
           "# pragma clang diagnostic ignored \"-Wnullability-extension\"\n"
           "#endif\n"
           "#if !__has_feature(nullability_nullable_result)\n"
           "# define _Nullable_result _Nullable\n"
           "#endif\n";
  }
}

static int compareImportModulesByName(const ImportModuleTy *left,
                                      const ImportModuleTy *right, bool isCxx) {
  auto *leftCodiraModule = left->dyn_cast<ModuleDecl *>();
  auto *rightCodiraModule = right->dyn_cast<ModuleDecl *>();

  if (leftCodiraModule && !rightCodiraModule)
    return -compareImportModulesByName(right, left, isCxx);

  if (leftCodiraModule && rightCodiraModule)
    return leftCodiraModule->getName().compare(rightCodiraModule->getName());

  auto *leftClangModule = left->get<const clang::Module *>();
  assert((isCxx || leftClangModule->isSubModule()) &&
         "top-level modules should use a normal language::ModuleDecl");
  if (rightCodiraModule) {
    // Because the Clang module is a submodule, its full name will never be
    // equal to a Codira module's name, even if the top-level name is the same;
    // it will always come before or after.
    if (leftClangModule->getTopLevelModuleName() <
        rightCodiraModule->getName().str()) {
      return -1;
    }
    return 1;
  }

  auto *rightClangModule = right->get<const clang::Module *>();
  assert((isCxx || rightClangModule->isSubModule()) &&
         "top-level modules should use a normal language::ModuleDecl");

  SmallVector<StringRef, 8> leftReversePath(
      ModuleDecl::ReverseFullNameIterator(leftClangModule), {});
  SmallVector<StringRef, 8> rightReversePath(
      ModuleDecl::ReverseFullNameIterator(rightClangModule), {});

  assert(leftReversePath != rightReversePath &&
         "distinct Clang modules should not have the same full name");
  if (std::lexicographical_compare(leftReversePath.rbegin(),
                                   leftReversePath.rend(),
                                   rightReversePath.rbegin(),
                                   rightReversePath.rend())) {
    return -1;
  }
  return 1;
}

// Makes the provided path absolute and removes any "." or ".." segments from
// the path
static toolchain::SmallString<128> normalizePath(const toolchain::StringRef path) {
  toolchain::SmallString<128> result = path;
  toolchain::sys::path::remove_dots(result, /* remove_dot_dot */ true);
  toolchain::sys::fs::make_absolute(result);
  return result;
}

// Collect the set of header includes needed to import the given Clang module
// into an ObjectiveC program. Modeled after collectModuleHeaderIncludes in the
// Clang frontend (FrontendAction.cpp)
// Augment requiredTextualIncludes with the set of headers required.
static void collectClangModuleHeaderIncludes(
    const clang::Module *clangModule, clang::FileManager &fileManager,
    toolchain::SmallSet<toolchain::SmallString<128>, 10> &requiredTextualIncludes,
    toolchain::SmallSet<const clang::Module *, 10> &visitedModules,
    const toolchain::SmallSet<toolchain::SmallString<128>, 10> &includeDirs,
    const toolchain::StringRef cwd) {

  if (!visitedModules.insert(clangModule).second)
    return;

  auto addHeader = [&](toolchain::StringRef headerPath,
                       toolchain::StringRef pathRelativeToRootModuleDir) {
    if (!clangModule->Directory)
      return;

    toolchain::SmallString<128> textualInclude = normalizePath(headerPath);
    toolchain::SmallString<128> containingSearchDirPath;

    for (auto &includeDir : includeDirs) {
      if (textualInclude.str().starts_with(includeDir)) {
        if (includeDir.size() > containingSearchDirPath.size()) {
          containingSearchDirPath = includeDir;
        }
      }
    }

    if (!containingSearchDirPath.empty()) {
      toolchain::SmallString<128> prefixToRemove =
          toolchain::formatv("{0}/", containingSearchDirPath);
      toolchain::sys::path::replace_path_prefix(textualInclude, prefixToRemove, "");
    } else {
      // If we cannot find find the module map on the search path,
      // fallback to including the header using the provided path relative
      // to the module map
      textualInclude = pathRelativeToRootModuleDir;
    }

    if (clangModule->getTopLevelModule()->IsFramework) {
      toolchain::SmallString<32> frameworkName =
          clangModule->getTopLevelModuleName();
      toolchain::SmallString<64> oldFrameworkPrefix =
          toolchain::formatv("{0}.framework/Headers", frameworkName);
      toolchain::sys::path::replace_path_prefix(textualInclude, oldFrameworkPrefix,
                                           frameworkName);
    }

    requiredTextualIncludes.insert(textualInclude);
  };

  if (std::optional<clang::Module::Header> umbrellaHeader =
          clangModule->getUmbrellaHeaderAsWritten()) {
    addHeader(umbrellaHeader->Entry.getFileEntry().tryGetRealPathName(),
        umbrellaHeader->PathRelativeToRootModuleDirectory);
  } else if (std::optional<clang::Module::DirectoryName> umbrellaDir =
                 clangModule->getUmbrellaDirAsWritten()) {
    SmallString<128> nativeUmbrellaDirPath;
    std::error_code errorCode;
    toolchain::sys::path::native(umbrellaDir->Entry.getName(),
                            nativeUmbrellaDirPath);
    toolchain::vfs::FileSystem &fileSystem = fileManager.getVirtualFileSystem();
    for (toolchain::vfs::recursive_directory_iterator
             dir(fileSystem, nativeUmbrellaDirPath, errorCode),
         end;
         dir != end && !errorCode; dir.increment(errorCode)) {

      if (toolchain::StringSwitch<bool>(toolchain::sys::path::extension(dir->path()))
              .Cases(".h", ".H", ".hh", ".hpp", true)
              .Default(false)) {

        // Compute path to the header relative to the root of the module
        // (location of the module map) First compute the relative path from
        // umbrella directory to header file
        SmallVector<StringRef> pathComponents;
        auto pathIt = toolchain::sys::path::rbegin(dir->path());

        for (int i = 0; i != dir.level() + 1; ++i, ++pathIt)
          pathComponents.push_back(*pathIt);
        // Then append this to the path from module root to umbrella dir
        SmallString<128> relativeHeaderPath;
        if (umbrellaDir->PathRelativeToRootModuleDirectory != ".")
          relativeHeaderPath += umbrellaDir->PathRelativeToRootModuleDirectory;

        for (auto it = pathComponents.rbegin(), end = pathComponents.rend();
             it != end; ++it) {
          toolchain::sys::path::append(relativeHeaderPath, *it);
        }

        addHeader(dir->path(), relativeHeaderPath);
      }
    }
  } else {
    for (clang::Module::HeaderKind headerKind :
         {clang::Module::HK_Normal, clang::Module::HK_Textual}) {
      for (const clang::Module::Header &header :
           clangModule->getHeaders(headerKind)) {
        addHeader(header.Entry.getFileEntry().tryGetRealPathName(),
                  header.PathRelativeToRootModuleDirectory);
      }
    }
    for (auto submodule : clangModule->submodules()) {
      if (submodule->IsExplicit)
        continue;

      collectClangModuleHeaderIncludes(submodule, fileManager,
                                       requiredTextualIncludes, visitedModules,
                                       includeDirs, cwd);
    }
  }
}

static void
writeImports(raw_ostream &out, toolchain::SmallPtrSetImpl<ImportModuleTy> &imports,
             ModuleDecl &M, StringRef bridgingHeader,
             const FrontendOptions &frontendOpts,
             clang::HeaderSearch &clangHeaderSearchInfo,
             const toolchain::StringMap<StringRef> &exposedModuleHeaderNames,
             bool useCxxImport = false,
             bool useNonModularIncludes = false) {
  useNonModularIncludes |= frontendOpts.EmitClangHeaderWithNonModularIncludes;

  // Note: we can't use has_feature(modules) as it's always enabled in C++20
  // mode.
  out << "#if __has_feature(objc_modules)\n";

  out << "#if __has_warning(\"-Watimport-in-framework-header\")\n"
      << "#pragma clang diagnostic ignored \"-Watimport-in-framework-header\"\n"
      << "#endif\n";

  // Sort alphabetically for determinism and consistency.
  SmallVector<ImportModuleTy, 8> sortedImports{imports.begin(),
                                               imports.end()};
  std::stable_sort(
      sortedImports.begin(), sortedImports.end(),
      [&](const ImportModuleTy &left, const ImportModuleTy &right) -> bool {
        return compareImportModulesByName(&left, &right, useCxxImport) < 0;
      });

  auto isUnderlyingModule = [&M, bridgingHeader](ModuleDecl *import) -> bool {
    if (bridgingHeader.empty())
      return import != &M && import->getName() == M.getName();

    return import->isClangHeaderImportModule();
  };

  clang::FileSystemOptions fileSystemOptions;
  clang::FileManager fileManager{fileSystemOptions};

  toolchain::SmallSet<toolchain::SmallString<128>, 10>
      requiredTextualIncludes; // Only included without modules.
  toolchain::SmallVector<StringRef, 1> textualIncludes; // always included.
  toolchain::SmallSet<const clang::Module *, 10> visitedModules;
  toolchain::SmallSet<toolchain::SmallString<128>, 10> includeDirs;

  toolchain::vfs::FileSystem &fileSystem = fileManager.getVirtualFileSystem();
  toolchain::ErrorOr<std::string> cwd = fileSystem.getCurrentWorkingDirectory();

  if (useNonModularIncludes) {
    assert(cwd && "Access to current working directory required");

    for (auto searchDir = clangHeaderSearchInfo.search_dir_begin();
         searchDir != clangHeaderSearchInfo.search_dir_end(); ++searchDir) {
      includeDirs.insert(normalizePath(searchDir->getName()));
    }

    const clang::Module *foundationModule = clangHeaderSearchInfo.lookupModule(
        "Foundation", clang::SourceLocation(), false, false);
    const clang::Module *darwinModule = clangHeaderSearchInfo.lookupModule(
        "Darwin", clang::SourceLocation(), false, false);

    std::function<void(const clang::Module *)>
        collectTransitiveSubmoduleClosure;
    collectTransitiveSubmoduleClosure = [&](const clang::Module *module) {
      if (!module)
        return;

      visitedModules.insert(module);
      for (auto submodule : module->submodules()) {
        collectTransitiveSubmoduleClosure(submodule);
      }
    };

    collectTransitiveSubmoduleClosure(foundationModule);
    collectTransitiveSubmoduleClosure(darwinModule);
  }

  // Track printed names to handle overlay modules.
  toolchain::SmallPtrSet<Identifier, 8> seenImports;
  bool includeUnderlying = false;
  StringRef importDirective =
      useCxxImport ? "#pragma clang module import" : "@import";
  StringRef importDirectiveLineEnd = useCxxImport ? "\n" : ";\n";
  for (auto import : sortedImports) {
    if (auto *languageModule = import.dyn_cast<ModuleDecl *>()) {
      if (useCxxImport) {
        // Do not import Codira modules into the C++ section of the generated
        // header unless explicitly exposed.
        auto it = exposedModuleHeaderNames.find(languageModule->getName().str());
        if (it != exposedModuleHeaderNames.end())
          textualIncludes.push_back(it->getValue());
        continue;
      }
      auto Name = languageModule->getName();
      if (isUnderlyingModule(languageModule)) {
        includeUnderlying = true;
        continue;
      }
      if (seenImports.insert(Name).second) {
        out << importDirective << ' ' << Name.str() << importDirectiveLineEnd;
        if (useNonModularIncludes) {
          if (const clang::Module *underlyingClangModule =
                  languageModule->findUnderlyingClangModule()) {
            collectClangModuleHeaderIncludes(
                underlyingClangModule, fileManager, requiredTextualIncludes,
                visitedModules, includeDirs, cwd.get());
          } else if ((underlyingClangModule =
                          clangHeaderSearchInfo.lookupModule(
                              Name.str(), clang::SourceLocation(), true,
                              true))) {
            collectClangModuleHeaderIncludes(
                underlyingClangModule, fileManager, requiredTextualIncludes,
                visitedModules, includeDirs, cwd.get());
          }
        }
      }
    } else {
      const auto *clangModule = import.get<const clang::Module *>();
      assert((useCxxImport || clangModule->isSubModule()) &&
             "top-level modules should use a normal language::ModuleDecl");
      out << importDirective << ' ';
      ModuleDecl::ReverseFullNameIterator(clangModule).printForward(out);
      out << importDirectiveLineEnd;
      if (useNonModularIncludes) {
        collectClangModuleHeaderIncludes(
            clangModule, fileManager, requiredTextualIncludes, visitedModules,
            includeDirs, cwd.get());
      }
    }
  }

  if (useNonModularIncludes && !requiredTextualIncludes.empty()) {
    out << "#elif defined(__OBJC__)\n";
    for (auto header : requiredTextualIncludes)
      out << "#import <" << header << ">\n";
    out << "#else\n";
    for (auto header : requiredTextualIncludes)
      out << "#include <" << header << ">\n";
  }
  out << "#endif\n\n";
  for (const auto header : textualIncludes) {
    out << "#include <" << header << ">\n";
  }

  if (includeUnderlying) {
    if (bridgingHeader.empty())
      out << "#import <" << M.getName().str() << '/' << M.getName().str()
          << ".h>\n\n";
    else {
      out << "#if defined(__OBJC__)\n";
      out << "#import \"" << bridgingHeader << "\"\n";
      out << "#else\n";
      out << "#include \"" << bridgingHeader << "\"\n";
      out << "#endif\n\n";
    }
  }
}

static void writePostImportPrologue(raw_ostream &os, ModuleDecl &M) {
  os << "#pragma clang diagnostic ignored \"-Wproperty-attribute-mismatch\"\n"
        "#pragma clang diagnostic ignored \"-Wduplicate-method-arg\"\n"
        "#if __has_warning(\"-Wpragma-clang-attribute\")\n"
        "# pragma clang diagnostic ignored \"-Wpragma-clang-attribute\"\n"
        "#endif\n"
        "#pragma clang diagnostic ignored \"-Wunknown-pragmas\"\n"
        "#pragma clang diagnostic ignored \"-Wnullability\"\n"
        "#pragma clang diagnostic ignored "
        "\"-Wdollar-in-identifier-extension\"\n"
        "#pragma clang diagnostic ignored "
        "\"-Wunsafe-buffer-usage\"\n"
        "\n"
        "#if __has_attribute(external_source_symbol)\n"
        "# pragma push_macro(\"any\")\n"
        "# undef any\n"
        "# pragma clang attribute push("
        "__attribute__((external_source_symbol(language=\"Codira\", "
        "defined_in=\""
     << M.getNameStr()
     << "\",generated_declaration))), "
        "apply_to=any(function,enum,objc_interface,objc_category,"
        "objc_protocol))\n"
        "# pragma pop_macro(\"any\")\n"
        "#endif\n\n";
}

static void writeObjCEpilogue(raw_ostream &os) {
  // Pop out of `external_source_symbol` attribute
  // before emitting the C++ section as the C++ section
  // might include other files in it.
  os << "#if __has_attribute(external_source_symbol)\n"
        "# pragma clang attribute pop\n"
        "#endif\n";
}

static void writeEpilogue(raw_ostream &os) {
  os << "#pragma clang diagnostic pop\n"
        // For the macro guard against recursive definition
        "#endif\n";
}

static std::string computeMacroGuard(const ModuleDecl *M) {
  return (toolchain::Twine(M->getNameStr().upper()) + "_LANGUAGE_H").str();
}

bool language::printAsClangHeader(raw_ostream &os, ModuleDecl *M,
                               StringRef bridgingHeader,
                               const FrontendOptions &frontendOpts,
                               const IRGenOptions &irGenOpts,
                               clang::HeaderSearch &clangHeaderSearchInfo) {
  toolchain::PrettyStackTraceString trace("While generating Clang header");

  CodiraToClangInteropContext interopContext(*M, irGenOpts);
  writePrologue(os, M->getASTContext(), computeMacroGuard(M));

  // C content (@cdecl)
  std::string moduleContentsScratch;
  if (M->getASTContext().LangOpts.hasFeature(Feature::CDecl)) {
    SmallPtrSet<ImportModuleTy, 8> imports;
    toolchain::raw_string_ostream cModuleContents{moduleContentsScratch};
    printModuleContentsAsC(cModuleContents, imports, *M, interopContext);

    toolchain::StringMap<StringRef> exposedModuleHeaderNames;
    writeImports(os, imports, *M, bridgingHeader, frontendOpts,
                 clangHeaderSearchInfo, exposedModuleHeaderNames,
                 /*useCxxImport=*/false, /*useNonModularIncludes*/true);

    emitExternC(os, [&] { os << "\n" << cModuleContents.str(); });
    moduleContentsScratch.clear();
  }

  // Objective-C content
  SmallPtrSet<ImportModuleTy, 8> imports;
  toolchain::raw_string_ostream objcModuleContents{moduleContentsScratch};
  printModuleContentsAsObjC(objcModuleContents, imports, *M, interopContext);
  emitObjCConditional(os, [&] {
    toolchain::StringMap<StringRef> exposedModuleHeaderNames;
    writeImports(os, imports, *M, bridgingHeader, frontendOpts,
                 clangHeaderSearchInfo, exposedModuleHeaderNames);
  });
  writePostImportPrologue(os, *M);
  emitObjCConditional(os, [&] { os << "\n" << objcModuleContents.str(); });
  writeObjCEpilogue(os);

  // C++ content
  emitCxxConditional(os, [&] {
    // FIXME: Expose Codira with @expose by default.
    bool enableCxx = frontendOpts.ClangHeaderExposedDecls.has_value() ||
                     M->DeclContext::getASTContext().LangOpts.EnableCXXInterop;
    if (!enableCxx)
      return;

    toolchain::StringSet<> exposedModules;
    for (const auto &mod : frontendOpts.clangHeaderExposedImports)
      exposedModules.insert(mod.moduleName);

    // Include the shim header only in the C++ mode.
    ClangSyntaxPrinter(M->getASTContext(), os).printIncludeForShimHeader(
        "_CodiraCxxInteroperability.h");

    // Explicit @expose attribute is required only when the user specifies
    // -clang-header-expose-decls flag.
    // FIXME: should we detect any presence of @expose and require it then?
    bool requiresExplicitExpose =
        frontendOpts.ClangHeaderExposedDecls.has_value() &&
        (*frontendOpts.ClangHeaderExposedDecls ==
             FrontendOptions::ClangHeaderExposeBehavior::HasExposeAttr ||
         *frontendOpts.ClangHeaderExposedDecls ==
             FrontendOptions::ClangHeaderExposeBehavior::
                 HasExposeAttrOrImplicitDeps);
    // Codira stdlib dependencies are emitted into the same header when
    // -clang-header-expose-decls flag is not specified, or when it allows
    // implicit dependency emission.
    bool addStdlibDepsInline =
        !frontendOpts.ClangHeaderExposedDecls.has_value() ||
        *frontendOpts.ClangHeaderExposedDecls ==
            FrontendOptions::ClangHeaderExposeBehavior::
                HasExposeAttrOrImplicitDeps ||
        *frontendOpts.ClangHeaderExposedDecls ==
            FrontendOptions::ClangHeaderExposeBehavior::AllPublic;

    std::string moduleContentsBuf;
    toolchain::raw_string_ostream moduleContents{moduleContentsBuf};
    auto deps = printModuleContentsAsCxx(
        moduleContents, *M, interopContext,
        /*requiresExposedAttribute=*/requiresExplicitExpose, exposedModules);
    // FIXME: In ObjC++ mode, we do not need to reimport duplicate modules.
    toolchain::StringMap<StringRef> exposedModuleHeaderNames;
    for (const auto &mod : frontendOpts.clangHeaderExposedImports)
      exposedModuleHeaderNames.insert({mod.moduleName, mod.headerName});
    writeImports(os, deps.imports, *M, bridgingHeader, frontendOpts,
                 clangHeaderSearchInfo, exposedModuleHeaderNames,
                 /*useCxxImport=*/true);
    // Embed the standard library directly.
    if (addStdlibDepsInline && deps.dependsOnStandardLibrary) {
      assert(!M->isStdlibModule());
      CodiraToClangInteropContext interopContext(
          *M->getASTContext().getStdlibModule(), irGenOpts);
      auto macroGuard = computeMacroGuard(M->getASTContext().getStdlibModule());
      os << "#ifndef " << macroGuard << "\n";
      os << "#define " << macroGuard << "\n";
      printModuleContentsAsCxx(
          os, *M->getASTContext().getStdlibModule(), interopContext,
          /*requiresExposedAttribute=*/true, exposedModules);
      os << "#endif // " << macroGuard << "\n";
    }

      os << moduleContents.str();
  });
  writeEpilogue(os);

  return false;
}
