' Copyright (c) 2024 Huawei Device Co., Ltd.
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
' http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml

participant Runtime

create Debugger
Runtime -> Debugger: instantiate singleton
Debugger --> Runtime: AddListener(this, DEBUG_EVENTS)

Runtime -> Runtime: dlopen(libarkinspector.so)

create Inspector
Runtime -> Inspector: StartDebugger()

create WebSocketServer
Inspector -> WebSocketServer: InitUnixWebSocket(), start server thread

loop while executing

    par
        WebSocketServer -> Inspector: CDP request
        Inspector -> Debugger: method implementation
        Debugger --> Inspector: result
        Inspector --> WebSocketServer: CDP response
    else
        Runtime -> Debugger: execution event
        Debugger -> Inspector: tooling event
        Inspector -> WebSocketServer: CDP event
    end

end

Runtime -> Inspector: StopDebugger()

Inspector -> WebSocketServer: CDP Runtime.executionContextsCleared event

Inspector -> WebSocketServer: Close()
WebSocketServer --> Inspector: join server thread
destroy WebSocketServer

Inspector --> Runtime: unload library
destroy Inspector

Runtime -> Debugger: destroy instance
Debugger --> Runtime: RemoveListener(this, DEBUG_EVENTS)
destroy Debugger

@enduml
