@startuml

enum VMType {
    DYNAMIC_VM
    STATIC_VM
}

enum TaskType {
    GC
    JIT
}

enum TaskExecutionMode {
    FOREGROUND
    BACKGROUND
}

class TaskProperties {
    VMType vm_type_
    TaskExecutionMode execution_mode_
}

Task : TaskType type_;
Task : RunnerType* runner_;
Task : TaskProperties properties_;

class TaskQueue

TaskQueue : size_t priority_
TaskQueue : TaskType type_
TaskQueue : Task[] tasks_ 
TaskQueue : AddTask(Task task)
TaskQueue : Task PopTask()

class ThreadManager

ThreadManager : TaskQueue[] tasq_queues_
ThreadManager : AddTask(TaskType task_type, Task task)

@enduml