@startuml

start

if (foreground_queue is empty and background_queue is empty?) then(yes)
  :Ask ThreadManager to fill foreground_queue and background_queue for Worker;
else(no)
endif

if (foreground_queue is not empty?) then(yes)
  :Run foreground_task;
elseif(background_queue is not empty?) then(no)
  :Run background_task;
endif

stop

@enduml