@startuml

title HybridVM startup and ThreadPool initialization

DynamicVM -> StaticVM : Create Static VM
DynamicVM -> StaticVM : InitStaticVM
StaticVM -> ThreadPool : Create shared ThreadPool
StaticVM -> ThreadPool : Register ArkTS GC queue
StaticVM -> ThreadPool : Register ArkTS JIT queue
DynamicVM -> ThreadPool : Register ECMA GC queue
StaticVM -> ThreadPool : Initialize thread pool
