@startuml

title Sequence diagram for worker 

"Worker 1" -> "Task Manager" : request for N tasks
"Task Manager" -> "GC Queue(ArkTS)" : request for X tasks in accordance with current distribution
"Task Manager" -> "GC Queue(Dynamic VM)" : request for Y tasks in accordance with current distribution
"Task Manager" -> "JIT Queue" : request for Z tasks in accordance with current distribution
"Task Manager" -> "Worker 1" : provide tasks in accordance with current distribution
"Worker 2" -> "Task Manager" : request for N tasks
"Task Manager" -> "GC Queue(ArkTS)" : request for X tasks in accordance with current distribution
"Task Manager" -> "GC Queue(Dynamic VM)" : request for Y tasks in accordance with current distribution
"Task Manager" -> "JIT Queue" : request for Z tasks in accordance with current distribution
"Task Manager" -> "Worker 2" : provide tasks in accordance with current distribution
"Worker 3" -> "Task Manager" : request for N tasks
"Task Manager" -> "GC Queue(ArkTS)" : ...

@enduml