# Copyright (c) 2021-2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//arkcompiler/runtime_core/static_core/ark_config.gni")
_plugin_dir = get_path_info(".", "abspath")
assert(string_replace(_plugin_dir, "//", "") != _plugin_dir)

enable_bytecode_optimizer = true

# TODO(nsizov): Fix after PR480 is merged
srcs_assembler = [ "assembler/extension/ets_meta.cpp" ]

srcs_compiler = [
  "compiler/ir_build_intrinsics_ets.cpp",
  "compiler/runtime_adapter_ets.cpp",
  "compiler/optimizer/ir_builder/ets_inst_builder.cpp",
  "compiler/optimizer/ets_codegen_extensions.cpp",
  "compiler/optimizer/ets_intrinsics_inlining_expansion.cpp",
  "compiler/optimizer/ets_intrinsics_peephole.cpp",
]

srcs_abc2program = [ "abc2program/abc2program_ets_plugin.cpp" ]

srcs_compiler += [ "compiler/codegen_intrinsics_ets.cpp" ]

srcs_disassembler = [ "disassembler/disasm_ets_plugin.cpp" ]

srcs_isa = [ "isa/isa.yaml" ]

srcs_verification = [ "verification/ets_plugin.cpp" ]

runtime_yamls = [
  "runtime/ets_libbase_runtime.yaml",
  "runtime/ets_compiler_intrinsics.yaml",
]

arkcompiler_deps = []
if (ark_ets_interop_js) {
  srcs_compiler += [
    "compiler/optimizer/ir_builder/js_interop/js_interop_inst_builder.cpp",
    "compiler/optimizer/optimizations/interop_js/interop_intrinsic_optimization.cpp",
  ]

  arkcompiler_deps +=
      [ "$ark_root/plugins/ets/runtime/interop_js:interop_intrinsic_kinds_h" ]

  runtime_yamls += [ "runtime/interop_js/intrinsics/std_js_jsruntime.yaml" ]
}

option_yaml_path = "ets_plugin_options.yaml"

runtime_option_yaml_path = [ "runtime_options.yaml" ]

inst_templates_yaml_path =
    "compiler/optimizer/ir_builder/ets_inst_templates.yaml"

entrypoints_yaml_path = "runtime/ets_entrypoints.yaml"

irtoc_scripts = [
  "irtoc_scripts/arrays.irt",
  "irtoc_scripts/to_string_cache.irt",
  "irtoc_scripts/typed_arrays.irt",
  "irtoc_scripts/escompat_array.irt",
  "irtoc_scripts/runtime.irt",
]

irtoc_plugins = [
  "irtoc_scripts/interpreter_handlers.irt",
  "irtoc_scripts/interpreter_main_loop.irt",
  "irtoc_scripts/string_builder.irt",
  "irtoc_scripts/string.irt",
]

arkbytecodeopt_deps =
    [ "$_plugin_dir:isa_gen_ets_bytecodeopt_ets_codegen_intrinsics_gen_inc" ]

arkruntime_deps = [
  "$ark_root/assembler:libarktsassembler_static",
  "$ark_root/libarkfile:libarktsfile_static",
]

arkcompiler_deps += [ "$_plugin_dir/runtime/interop_js:interop_intrinsic_kinds_h(${default_toolchain})" ]

srcs_runtime = [
  "dfx/heap_helpers.cpp",
  "runtime/ani/ani_interaction_api.cpp",
  "runtime/ani/ani_mangle.cpp",
  "runtime/ani/ani_options.cpp",
  "runtime/ani/ani_options_parser.cpp",
  "runtime/ani/ani_vm_api.cpp",
  "runtime/ani/verify/ani_verifier.cpp",
  "runtime/ani/verify/env_ani_verifier.cpp",
  "runtime/ani/verify/types/internal_ref.cpp",
  "runtime/ani/verify/types/venv.cpp",
  "runtime/ani/verify/types/vmethod.cpp",
  "runtime/ani/verify/types/vfield.cpp",
  "runtime/ani/verify/types/vref.cpp",
  "runtime/ani/verify/verify_ani_checker.cpp",
  "runtime/ani/verify/verify_ani_interaction_api.cpp",
  "runtime/ani/verify/verify_ani_vm_api.cpp",
  "runtime/ets_annotation.cpp",
  "runtime/ets_class_linker.cpp",
  "runtime/ets_class_linker_context.cpp",
  "runtime/ets_class_linker_extension.cpp",
  "runtime/ets_coroutine.cpp",
  "runtime/ets_entrypoints.cpp",
  "runtime/ets_exceptions.cpp",
  "runtime/ets_itable_builder.cpp",
  "runtime/ets_language_context.cpp",
  "runtime/ets_napi_env.cpp",
  "runtime/ets_native_library.cpp",
  "runtime/ets_native_library_provider.cpp",
  "runtime/ets_namespace_manager.cpp",
  "runtime/ets_namespace_manager_impl.cpp",
  "runtime/ets_object_state_info.cpp",
  "runtime/ets_object_state_table.cpp",
  "runtime/ets_platform_types.cpp",
  "runtime/ets_runtime_interface.cpp",
  "runtime/ets_stdlib_cache.cpp",
  "runtime/ets_stubs.cpp",
  "runtime/ets_vm.cpp",
  "runtime/ets_vm_api.cpp",  # TODO(nsizov): Take into account PR640, if needed
  "runtime/ets_vtable_builder.cpp",
  "runtime/finalreg/finalization_registry_manager.cpp",
  "runtime/unhandled_manager/unhandled_object_manager.cpp",
  "runtime/integrate/ark_vm_api.cpp",
  "runtime/integrate/ets_ani_expo.cpp",
  "runtime/intrinsics/escompat_Array.cpp",
  "runtime/intrinsics/escompat_ArrayBuffer.cpp",
  "runtime/intrinsics/std_core_RegExp.cpp",
  "runtime/intrinsics/escompat_TypedArrays.cpp",
  "runtime/intrinsics/escompat_Map.cpp",
  "runtime/intrinsics/std_containers_WeakMap.cpp",
  "runtime/intrinsics/std_core_Set.cpp",
  "runtime/intrinsics/compiler_intrinsics.cpp",
  "runtime/intrinsics/debugger_api.cpp",
  "runtime/intrinsics/escompat_Date.cpp",
  "runtime/intrinsics/std_core_JSON.cpp",
  "runtime/intrinsics/std_concurrency_taskpool.cpp",
  "runtime/intrinsics/escompat_Reflect.cpp",
  "runtime/intrinsics/std_core.cpp",
  "runtime/intrinsics/std_core_Char.cpp",
  "runtime/intrinsics/std_core_Arrays.cpp",
  "runtime/intrinsics/std_core_Job.cpp",
  "runtime/intrinsics/std_concurrency_Launch.cpp",
  "runtime/intrinsics/std_core_Class.cpp",
  "runtime/intrinsics/std_core_AbcFile.cpp",
  "runtime/intrinsics/std_core_AbcRuntimeLinker.cpp",
  "runtime/intrinsics/std_core_Console.cpp",
  "runtime/intrinsics/std_core_Byte.cpp",
  "runtime/intrinsics/std_core_Short.cpp",
  "runtime/intrinsics/std_core_Int.cpp",
  "runtime/intrinsics/std_core_Long.cpp",
  "runtime/intrinsics/std_core_Double.cpp",
  "runtime/intrinsics/std_core_ExclusiveLauncher.cpp",
  "runtime/intrinsics/std_core_Float.cpp",
  "runtime/intrinsics/std_core_Promise.cpp",
  "runtime/intrinsics/std_core_StackTrace.cpp",
  "runtime/intrinsics/std_concurrency_Atomics.cpp",
  "runtime/intrinsics/gc_task_tracker.cpp",
  "runtime/intrinsics/std_core_AniHelpers.cpp",
  "runtime/intrinsics/std_core_Runtime.cpp",
  "runtime/intrinsics/std_core_SyncPrimitives.cpp",
  "runtime/intrinsics/std_core_String.cpp",
  "runtime/intrinsics/std_core_StringBuilder.cpp",
  "runtime/intrinsics/std_core_Timers.cpp",
  "runtime/intrinsics/std_core_Type.cpp",
  "runtime/intrinsics/std_core_TypeCreator.cpp",
  "runtime/intrinsics/reflect_Proxy.cpp",
  "runtime/intrinsics/std_core_Method.cpp",
  "runtime/intrinsics/std_core_reflect_Method.cpp",
  "runtime/intrinsics/std_core_reflect_Field.cpp",
  "runtime/intrinsics/std_core_reflect_internals.cpp",
  "runtime/intrinsics/std_core_Value.cpp",
  "runtime/intrinsics/std_core_gc.cpp",
  "runtime/intrinsics/std_core_finalization_registry.cpp",
  "runtime/intrinsics/std_math.cpp",
  "runtime/intrinsics/unsafe_memory.cpp",
  "runtime/intrinsics/helpers/dtoa_helper.cpp",
  "runtime/intrinsics/helpers/array_buffer_helper.cpp",
  "runtime/intrinsics/helpers/ets_intrinsics_helpers.cpp",
  "runtime/intrinsics/helpers/reflection_helpers.cpp",
  "runtime/intrinsics/helpers/ets_string_case_conversion.cpp",
  "runtime/intrinsics/helpers/ets_string_helpers.cpp",
  "runtime/intrinsics/helpers/ets_to_string_cache.cpp",
  "runtime/intrinsics/helpers/json_helper.cpp",
  "runtime/main_worker_external_scheduler.cpp",
  "runtime/mem/ets_gc_stat.cpp",
  "runtime/mem/ets_reference_processor.cpp",
  "runtime/ani/ani_helpers.cpp",
  "runtime/types/ets_class.cpp",
  "runtime/types/ets_arraybuffer.cpp",
  "runtime/types/ets_escompat_array.cpp",
  "runtime/types/ets_field.cpp",
  "runtime/types/ets_method.cpp",
  "runtime/types/ets_job.cpp",
  "runtime/types/ets_promise.cpp",
  "runtime/types/ets_promise_ref.cpp",
  "runtime/types/ets_object.cpp",
  "runtime/types/ets_sync_primitives.cpp",
  "runtime/types/ets_string_builder.cpp",
  "runtime/types/ets_string.cpp",
  "runtime/types/ets_typeapi_parameter.cpp",
  "runtime/types/ets_typeapi_method.cpp",
  "runtime/types/ets_reflect_method.cpp",
  "runtime/types/ets_typeapi_field.cpp",
  "runtime/types/ets_reflect_field.cpp",
  "runtime/types/ets_typeapi_create.cpp",
  "runtime/types/ets_waiters_list.cpp",
  "runtime/types/ets_finalizable_weak_ref.cpp",
  "runtime/types/ets_finreg_node.cpp",
  "runtime/types/ets_finalization_registry.cpp",
  "runtime/types/ets_map.cpp",
  "runtime/ets_utils.cpp",
  "runtime/static_object_accessor.cpp",
  "runtime/static_type_converter.cpp",
  "runtime/entrypoints/ets_proxy_entrypoints.cpp",
  "stdlib/native/init_native_methods.cpp",
  "stdlib/native/core/regexp/RegExp.cpp",
  "stdlib/native/core/regexp/regexp_executor.cpp",
  "stdlib/native/core/regexp/regexp_16.cpp",
  "stdlib/native/core/regexp/regexp_8.cpp",
  "stdlib/native/core/Intl.cpp",
  "stdlib/native/core/IntlCommon.cpp",
  "stdlib/native/core/IntlState.cpp",
  "stdlib/native/core/IntlNumberFormat.cpp",
  "stdlib/native/core/IntlNumberFormatters.cpp",
  "stdlib/native/core/IntlFormattersCache.cpp",
  "stdlib/native/core/IntlLocale.cpp",
  "stdlib/native/core/IntlLocaleHelper.cpp",
  "stdlib/native/core/IntlLocaleMatch.cpp",
  "stdlib/native/core/IntlCollator.cpp",
  "stdlib/native/core/IntlCollatorCache.cpp",
  "stdlib/native/core/IntlPluralRules.cpp",
  "stdlib/native/core/IntlSegmenter.cpp",
  "stdlib/native/core/IntlDisplayNames.cpp",
  "stdlib/native/core/Process.cpp",
  "stdlib/native/core/stdlib_ani_helpers.cpp",
  "stdlib/native/core/IntlDateTimeFormatCache.cpp",
  "stdlib/native/etsstdlib.cpp",
  "stdlib/native/core/IntlDateTimeFormat.cpp",
  "stdlib/native/core/IntlListFormat.cpp",
  "stdlib/native/core/IntlRelativeTimeFormat.cpp",
  "stdlib/native/core/IntlRelativeTimeFormatCache.cpp",
  "stdlib/native/core/IntlLanguageTag.cpp",
]

if (ark_hybrid) {
  srcs_runtime += [
    "runtime/hybrid/mem/external-gc.cpp",
    "runtime/hybrid/mem/static_object_operator.cpp",
  ]
}

if (is_ohos) {
  srcs_runtime += [ "runtime/platform/ohos/logger.cpp" ]
}

configs_runtime = []

if (ark_ets_interop_js) {
  runtime_option_yaml_path += [ "runtime/interop_js/runtime_options.yaml" ]
  srcs_runtime += [
    "runtime/interop_js/call/call_ets.cpp",
    "runtime/interop_js/call/call_js.cpp",
    "runtime/interop_js/code_scopes.cpp",
    "runtime/interop_js/ets_proxy/ets_class_wrapper.cpp",
    "runtime/interop_js/ets_proxy/ets_field_wrapper.cpp",
    "runtime/interop_js/ets_proxy/ets_method_set.cpp",
    "runtime/interop_js/ets_proxy/ets_method_wrapper.cpp",
    "runtime/interop_js/ets_proxy/ets_proxy.cpp",
    "runtime/interop_js/ets_proxy/shared_reference.cpp",
    "runtime/interop_js/ets_proxy/shared_reference_storage.cpp",
    "runtime/interop_js/ets_proxy/shared_reference_storage_verifier.cpp",
    "runtime/interop_js/event_loop_module.cpp",
    "runtime/interop_js/st_value/ets_vm_STValue.cpp",
    "runtime/interop_js/st_value/ets_vm_STValue_check.cpp",
    "runtime/interop_js/st_value/ets_vm_STValue_instance.cpp",
    "runtime/interop_js/st_value/ets_vm_STValue_invoke.cpp",
    "runtime/interop_js/st_value/ets_vm_STValue_accessor.cpp",
    "runtime/interop_js/st_value/ets_vm_STValue_unwrap.cpp",
    "runtime/interop_js/st_value/ets_vm_STValue_wrap.cpp",
    "runtime/interop_js/st_value/ets_vm_STValue_param_getter.cpp",
    "runtime/interop_js/timer_helper/timer.cpp",
    "runtime/interop_js/timer_helper/interop_timer_helper.cpp",
    "runtime/interop_js/interop_common.cpp",
    "runtime/interop_js/interop_context.cpp",
    "runtime/interop_js/intrinsics/std_js_jsruntime.cpp",
    "runtime/interop_js/intrinsics_api_impl.cpp",
    "runtime/interop_js/js_job_queue.cpp",
    "runtime/interop_js/js_proxy/js_proxy.cpp",
    "runtime/interop_js/js_refconvert.cpp",
    "runtime/interop_js/js_refconvert_builtin.cpp",
    "runtime/interop_js/js_refconvert_function.cpp",
    "runtime/interop_js/js_refconvert_union.cpp",
    "runtime/interop_js/js_refconvert_record.cpp",
    "runtime/interop_js/js_refconvert_tuple.cpp",
    "runtime/interop_js/js_value.cpp",
    "runtime/interop_js/napi_impl/napi_impl.cpp",
    "runtime/interop_js/native_api/arkts_interop_js_api_impl.cpp",
    "runtime/interop_js/stack_info.cpp",
    "runtime/interop_js/sts_vm_interface_impl.cpp",
    "runtime/interop_js/timer_module.cpp",
    "runtime/interop_js/xgc/xgc.cpp",
    "runtime/interop_js/xgc/xgc_vm_adaptor.cpp",
    "runtime/interop_js/xref_object_operator.cpp",
  ]

  if (ark_ets_hybrid) {
    srcs_runtime += [ "runtime/interop_js/handshake.cpp" ]
  }

  if (current_cpu == "amd64" || current_cpu == "x64" ||
      current_cpu == "x86_64") {
    srcs_runtime += [ "runtime/interop_js/arch/amd64/call_bridge_amd64.S" ]
  } else if (current_cpu == "arm64") {
    srcs_runtime += [ "runtime/interop_js/arch/arm64/call_bridge_aarch64.S" ]
  } else if (current_cpu == "arm") {
    srcs_runtime += [ "runtime/interop_js/arch/arm32/call_bridge_arm32.S" ]
  }

  configs_runtime += [ "runtime/interop_js:interop_js_public_config" ]

  arkruntime_deps += [ "$platform_root:libplatform" ]

  if (ark_standalone_build && ark_ets_hybrid) {
    arkruntime_deps += [
      "$ark_third_party_root/libuv:uv",
      "$arkui_root/napi:ace_napi",
    ]
  }
}

if (current_cpu == "amd64" || current_cpu == "x64" || current_cpu == "x86_64") {
  srcs_runtime += [
    "runtime/ani/arch/amd64/ets_napi_entry_point_amd64.S",
    "runtime/ani/arch/amd64/ets_async_entry_point_amd64.S",
    "runtime/entrypoints/arch/amd64/ets_proxy_entry_point_amd64.S",
  ]
} else if (current_cpu == "arm64") {
  srcs_runtime += [
    "runtime/ani/arch/arm64/ets_napi_entry_point_aarch64.S",
    "runtime/ani/arch/arm64/ets_async_entry_point_aarch64.S",
    "runtime/entrypoints/arch/arm64/ets_proxy_entry_point_aarch64.S",
  ]
} else if (current_cpu == "arm") {
  srcs_runtime += [
    "runtime/ani/arch/arm32/ets_napi_entry_point_arm32.S",
    "runtime/ani/arch/arm32/ets_async_entry_point_arm32.S",
    "runtime/entrypoints/arch/arm32/ets_proxy_entry_point_arm32.S",
  ]
}

# TODO(nsizov): Support 32-bit ARM

# Tests list
unittests_list = [
  "tests/runtime/types:ets_internal_objects_mock_tests",
  "tests/runtime/types:ets_internal_objects_tests",
]
