' Copyright (c) 2024 Huawei Device Co., Ltd.
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
' http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.

@startuml

participant Runtime
participant RuntimeNotificationManager
participant Sampler
participant ListenerThread
participant SamplerThread

Runtime -> Sampler: Create

Sampler -> RuntimeNotificationManager: AddListener(instance_, THREAD_EVENTS | LOAD_MODULE)
Sampler --> Runtime: instance_

Runtime -> Sampler: Start

Sampler -> ListenerThread: create
Sampler -> SamplerThread: create

loop while sampling
    loop for each application thread
        SamplerThread -> SamplerThread: collect thread sample
    end
    SamplerThread -> SamplerThread: sleep(samplingInterval_)
end

Runtime -> Sampler: Stop

Sampler <-- ListenerThread: join
Sampler <-- SamplerThread: join

Runtime -> Sampler: Destroy

Sampler -> RuntimeNotificationManager: RemoveListener(instance_, THREAD_EVENTS | LOAD_MODULE)

@enduml
