/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

// Autogenerated file by gen_null_arg_tests.rb script -- DO NOT EDIT!

#include "libabckit/c/abckit.h"
#include "libabckit/c/metadata_core.h"
#include "libabckit/c/extensions/arkts/metadata_arkts.h"
#include "libabckit/c/extensions/js/metadata_js.h"
#include "libabckit/c/ir_core.h"
#include "libabckit/c/isa/isa_dynamic.h"
#include "libabckit/c/isa/isa_static.h"

#include "helpers/helpers.h"
#include "helpers/helpers_nullptr.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_jsModifyApiImp = AbckitGetJsModifyApiImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitNullptrTestsJsModifyApiImpl0 : public ::testing::Test {};

// Test: test-kind=api, api=JsModifyApiImpl::fileAddExternalModule,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsJsModifyApiImpl0, fileAddExternalModule)
{
    helpers_nullptr::TestNullptr(g_jsModifyApiImp->fileAddExternalModule);
}

// Test: test-kind=api, api=JsModifyApiImpl::moduleAddExportFromJsToJs,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsJsModifyApiImpl0, moduleAddExportFromJsToJs)
{
    helpers_nullptr::TestNullptr(g_jsModifyApiImp->moduleAddExportFromJsToJs);
}

// Test: test-kind=api, api=JsModifyApiImpl::moduleAddImportFromJsToJs,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsJsModifyApiImpl0, moduleAddImportFromJsToJs)
{
    helpers_nullptr::TestNullptr(g_jsModifyApiImp->moduleAddImportFromJsToJs);
}

// Test: test-kind=api, api=JsModifyApiImpl::moduleRemoveExport,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsJsModifyApiImpl0, moduleRemoveExport)
{
    helpers_nullptr::TestNullptr(g_jsModifyApiImp->moduleRemoveExport);
}

// Test: test-kind=api, api=JsModifyApiImpl::moduleRemoveImport,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsJsModifyApiImpl0, moduleRemoveImport)
{
    helpers_nullptr::TestNullptr(g_jsModifyApiImp->moduleRemoveImport);
}

}  // namespace libabckit::test
