/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

// Autogenerated file by gen_null_arg_tests.rb script -- DO NOT EDIT!

#include "libabckit/c/abckit.h"
#include "libabckit/c/metadata_core.h"
#include "libabckit/c/extensions/arkts/metadata_arkts.h"
#include "libabckit/c/extensions/js/metadata_js.h"
#include "libabckit/c/ir_core.h"
#include "libabckit/c/isa/isa_dynamic.h"
#include "libabckit/c/isa/isa_static.h"

#include "helpers/helpers.h"
#include "helpers/helpers_nullptr.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_arktsModifyApiImp = AbckitGetArktsModifyApiImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitNullptrTestsArktsModifyApiImpl0 : public ::testing::Test {};

// Test: test-kind=api, api=ArktsModifyApiImpl::annotationAddAnnotationElement,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, annotationAddAnnotationElement)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->annotationAddAnnotationElement);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::annotationInterfaceAddField,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, annotationInterfaceAddField)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->annotationInterfaceAddField);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::annotationInterfaceRemoveField,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, annotationInterfaceRemoveField)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->annotationInterfaceRemoveField);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::annotationRemoveAnnotationElement,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, annotationRemoveAnnotationElement)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->annotationRemoveAnnotationElement);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classAddAnnotation,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classAddAnnotation)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classAddAnnotation);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classRemoveAnnotation,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classRemoveAnnotation)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classRemoveAnnotation);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classRemoveField,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classRemoveField)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classRemoveField);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceAddField,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceAddField)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceAddField);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceAddMethod,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceAddMethod)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceAddMethod);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classSetName,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classSetName)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classSetName);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classAddField,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classAddField)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classAddField);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classSetOwningModule,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classSetOwningModule)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classSetOwningModule);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceAddSuperInterface,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceAddSuperInterface)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceAddSuperInterface);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceRemoveSuperInterface,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceRemoveSuperInterface)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceRemoveSuperInterface);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceRemoveMethod,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceRemoveMethod)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceRemoveMethod);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceSetOwningModule,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceSetOwningModule)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceSetOwningModule);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::fileAddExternalModuleArktsV1,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, fileAddExternalModuleArktsV1)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->fileAddExternalModuleArktsV1);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::functionAddAnnotation,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, functionAddAnnotation)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->functionAddAnnotation);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceSetName,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceSetName)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceSetName);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::functionRemoveAnnotation,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, functionRemoveAnnotation)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->functionRemoveAnnotation);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::moduleAddAnnotationInterface,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, moduleAddAnnotationInterface)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->moduleAddAnnotationInterface);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::moduleAddField,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, moduleAddField)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->moduleAddField);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::moduleFieldSetName,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, moduleFieldSetName)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->moduleFieldSetName);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classFieldAddAnnotation,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classFieldAddAnnotation)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classFieldAddAnnotation);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classFieldRemoveAnnotation,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classFieldRemoveAnnotation)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classFieldRemoveAnnotation);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classFieldSetName,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classFieldSetName)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classFieldSetName);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::moduleAddExportFromArktsV1ToArktsV1,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, moduleAddExportFromArktsV1ToArktsV1)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->moduleAddExportFromArktsV1ToArktsV1);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::moduleAddImportFromArktsV1ToArktsV1,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, moduleAddImportFromArktsV1ToArktsV1)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->moduleAddImportFromArktsV1ToArktsV1);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::moduleRemoveExport,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, moduleRemoveExport)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->moduleRemoveExport);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::moduleRemoveImport,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, moduleRemoveImport)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->moduleRemoveImport);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::AbckitGetArktsModifyApiImpl,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, AbckitGetArktsModifyApiImpl)
{
    helpers_nullptr::TestNullptr(AbckitGetArktsModifyApiImpl);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceRemoveField,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceRemoveField)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceRemoveField);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::createClass,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, createClass)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->createClass);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classRemoveMethod,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classRemoveMethod)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classRemoveMethod);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classAddInterface,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classAddInterface)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classAddInterface);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classRemoveInterface,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classRemoveInterface)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classRemoveInterface);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classSetSuperClass,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classSetSuperClass)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classSetSuperClass);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::createInterface,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, createInterface)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->createInterface);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classFieldSetType,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classFieldSetType)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classFieldSetType);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::classFieldSetValue,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, classFieldSetValue)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->classFieldSetValue);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::moduleFieldSetType,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, moduleFieldSetType)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->moduleFieldSetType);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::moduleFieldSetValue,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, moduleFieldSetValue)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->moduleFieldSetValue);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceFieldAddAnnotation,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceFieldAddAnnotation)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceFieldAddAnnotation);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceFieldRemoveAnnotation,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceFieldRemoveAnnotation)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceFieldRemoveAnnotation);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceFieldSetName,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceFieldSetName)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceFieldSetName);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::interfaceFieldSetType,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, interfaceFieldSetType)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->interfaceFieldSetType);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::enumFieldSetName,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, enumFieldSetName)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->enumFieldSetName);
}

// Test: test-kind=api, api=ArktsModifyApiImpl::enumAddField,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsArktsModifyApiImpl0, enumAddField)
{
    helpers_nullptr::TestNullptr(g_arktsModifyApiImp->enumAddField);
}
}  // namespace libabckit::test
