/*
 * Copyright (c) NeXTHub Corporation. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201,
 * Middletown, DE 19709, New Castle County, USA.
 */

// Autogenerated file by gen_null_arg_tests.rb script -- DO NOT EDIT!

#include "libabckit/c/abckit.h"
#include "libabckit/c/metadata_core.h"
#include "libabckit/c/extensions/arkts/metadata_arkts.h"
#include "libabckit/c/extensions/js/metadata_js.h"
#include "libabckit/c/ir_core.h"
#include "libabckit/c/isa/isa_dynamic.h"
#include "libabckit/c/isa/isa_static.h"

#include "helpers/helpers.h"
#include "helpers/helpers_nullptr.h"

#include <gtest/gtest.h>

namespace libabckit::test {

static auto g_inspectApiImp = AbckitGetInspectApiImpl(ABCKIT_VERSION_RELEASE_1_0_0);

class LibAbcKitNullptrTestsInspectApiImpl1 : public ::testing::Test {};

// Test: test-kind=api, api=InspectApiImpl::interfaceFieldEnumerateAnnotations,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, interfaceFieldEnumerateAnnotations)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->interfaceFieldEnumerateAnnotations);
}

// Test: test-kind=api, api=InspectApiImpl::interfaceFieldGetInterface,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, interfaceFieldGetInterface)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->interfaceFieldGetInterface);
}

// Test: test-kind=api, api=InspectApiImpl::interfaceFieldGetName,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, interfaceFieldGetName)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->interfaceFieldGetName);
}

// Test: test-kind=api, api=InspectApiImpl::interfaceFieldGetType,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, interfaceFieldGetType)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->interfaceFieldGetType);
}

// Test: test-kind=api, api=InspectApiImpl::interfaceFieldIsReadonly,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, interfaceFieldIsReadonly)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->interfaceFieldIsReadonly);
}

// Test: test-kind=api, api=InspectApiImpl::interfaceGetFile,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, interfaceGetFile)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->interfaceGetFile);
}

// Test: test-kind=api, api=InspectApiImpl::interfaceGetModule,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, interfaceGetModule)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->interfaceGetModule);
}

// Test: test-kind=api, api=InspectApiImpl::interfaceGetName,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, interfaceGetName)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->interfaceGetName);
}

// Test: test-kind=api, api=InspectApiImpl::interfaceGetParentNamespace,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, interfaceGetParentNamespace)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->interfaceGetParentNamespace);
}

// Test: test-kind=api, api=InspectApiImpl::interfaceIsExternal,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, interfaceIsExternal)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->interfaceIsExternal);
}

// Test: test-kind=api, api=InspectApiImpl::literalArrayEnumerateElements,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalArrayEnumerateElements)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalArrayEnumerateElements);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetBool,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetBool)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetBool);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetDouble,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetDouble)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetDouble);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetFile,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetFile)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetFile);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetFloat,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetFloat)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetFloat);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetLiteralArray,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetLiteralArray)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetLiteralArray);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetMethod,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetMethod)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetMethod);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetMethodAffiliate,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetMethodAffiliate)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetMethodAffiliate);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetString,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetString)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetString);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetTag,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetTag)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetTag);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetU16,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetU16)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetU16);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetU32,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetU32)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetU32);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetU64,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetU64)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetU64);
}

// Test: test-kind=api, api=InspectApiImpl::literalGetU8,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, literalGetU8)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->literalGetU8);
}

// Test: test-kind=api, api=InspectApiImpl::moduleEnumerateAnnotationInterfaces,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleEnumerateAnnotationInterfaces)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleEnumerateAnnotationInterfaces);
}

// Test: test-kind=api, api=InspectApiImpl::moduleEnumerateAnonymousFunctions,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleEnumerateAnonymousFunctions)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleEnumerateAnonymousFunctions);
}

// Test: test-kind=api, api=InspectApiImpl::moduleEnumerateClasses,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleEnumerateClasses)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleEnumerateClasses);
}

// Test: test-kind=api, api=InspectApiImpl::moduleEnumerateEnums,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleEnumerateEnums)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleEnumerateEnums);
}

// Test: test-kind=api, api=InspectApiImpl::moduleEnumerateExports,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleEnumerateExports)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleEnumerateExports);
}

// Test: test-kind=api, api=InspectApiImpl::moduleEnumerateFields,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleEnumerateFields)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleEnumerateFields);
}

// Test: test-kind=api, api=InspectApiImpl::moduleEnumerateImports,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleEnumerateImports)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleEnumerateImports);
}

// Test: test-kind=api, api=InspectApiImpl::moduleEnumerateInterfaces,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleEnumerateInterfaces)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleEnumerateInterfaces);
}

// Test: test-kind=api, api=InspectApiImpl::moduleEnumerateNamespaces,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleEnumerateNamespaces)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleEnumerateNamespaces);
}

// Test: test-kind=api, api=InspectApiImpl::moduleEnumerateTopLevelFunctions,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleEnumerateTopLevelFunctions)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleEnumerateTopLevelFunctions);
}

// Test: test-kind=api, api=InspectApiImpl::moduleFieldGetModule,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleFieldGetModule)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleFieldGetModule);
}

// Test: test-kind=api, api=InspectApiImpl::moduleFieldGetName,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleFieldGetName)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleFieldGetName);
}

// Test: test-kind=api, api=InspectApiImpl::moduleFieldGetType,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleFieldGetType)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleFieldGetType);
}

// Test: test-kind=api, api=InspectApiImpl::moduleGetFile,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleGetFile)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleGetFile);
}

// Test: test-kind=api, api=InspectApiImpl::moduleGetName,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleGetName)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleGetName);
}

// Test: test-kind=api, api=InspectApiImpl::moduleGetTarget,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleGetTarget)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleGetTarget);
}

// Test: test-kind=api, api=InspectApiImpl::moduleIsExternal,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, moduleIsExternal)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->moduleIsExternal);
}

// Test: test-kind=api, api=InspectApiImpl::typeGetName,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, typeGetName)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->typeGetName);
}

// Test: test-kind=api, api=InspectApiImpl::typeGetRank,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, typeGetRank)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->typeGetRank);
}

// Test: test-kind=api, api=InspectApiImpl::typeIsUnion,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, typeIsUnion)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->typeIsUnion);
}

// Test: test-kind=api, api=InspectApiImpl::typeEnumerateUnionTypes,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, typeEnumerateUnionTypes)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->typeEnumerateUnionTypes);
}

// Test: test-kind=api, api=InspectApiImpl::typeGetReferenceClass,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, typeGetReferenceClass)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->typeGetReferenceClass);
}

// Test: test-kind=api, api=InspectApiImpl::typeGetTypeId,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, typeGetTypeId)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->typeGetTypeId);
}

// Test: test-kind=api, api=InspectApiImpl::valueGetDouble,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, valueGetDouble)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->valueGetDouble);
}

// Test: test-kind=api, api=InspectApiImpl::valueGetFile,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, valueGetFile)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->valueGetFile);
}

// Test: test-kind=api, api=InspectApiImpl::valueGetString,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, valueGetString)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->valueGetString);
}

// Test: test-kind=api, api=InspectApiImpl::valueGetType,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, valueGetType)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->valueGetType);
}

// Test: test-kind=api, api=InspectApiImpl::valueGetU1,
// abc-kind=NoABC, category=negative-nullptr, extension=c
TEST_F(LibAbcKitNullptrTestsInspectApiImpl1, valueGetU1)
{
    helpers_nullptr::TestNullptr(g_inspectApiImp->valueGetU1);
}

}  // namespace libabckit::test
