[package]
name = "codira_vfs"
description = "Provides an in-memory filesystem"
keywords = ["game", "hot-reloading", "language", "codira", "scripting"]
categories.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
codira_paths = { version = "0.6.0-dev", path="../codira_paths" }
crossbeam-channel = { workspace = true }
log = { workspace = true }
notify = { workspace = true }
rustc-hash = { workspace = true }
walkdir = { workspace = true }
