/**
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export declare const testInterface: TestInterface;
export declare const tsString: string;
export declare const tsNumberToByteLR: number;
export declare const tsNumberToByteRR: number;
export declare const tsNumberToIntLR: number;
export declare const tsNumberToIntRR: number;
export declare const tsNumberToShortLR: number;
export declare const tsNumberToShortRR: number;
export declare const tsNumberToLongLR: number;
export declare const tsNumberToLongRR: number;
export declare const tsNumberToCharLR: number;
export declare const tsNumberToCharRR: number;
export declare const tsBoolean: boolean;
export declare const tsNull: null;
export declare const tsUndefined: undefined;
export declare const tsBigInt: bigint;
export declare const tsArrayNum: number[];
export declare const tsArrayStr: string[];
interface TestInterface {
    testNumber: number;
    testString: string;
}
