set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "")
set(BUILD_SHARED_LIBS YES CACHE BOOL "")

set(CodiraCore_ENABLE_BACKTRACING ON CACHE BOOL "")
set(CodiraCore_ENABLE_COMMANDLINE_SUPPORT ON CACHE BOOL "")
set(CodiraCore_ENABLE_CRASH_REPORTER_CLIENT ON CACHE BOOL "")
set(CodiraCore_ENABLE_LIBRARY_EVOLUTION ON CACHE BOOL "")
set(CodiraCore_ENABLE_OBJC_INTEROP ON CACHE BOOL "")
set(CodiraCore_ENABLE_REFLECTION ON CACHE BOOL "")
set(CodiraCore_ENABLE_TYPE_PRINTING ON CACHE BOOL "")
set(CodiraCore_ENABLE_VECTOR_TYPES ON CACHE BOOL "")
set(CodiraCore_ENABLE_RUNTIME_FUNCTION_COUNTERS ON CACHE BOOL "")
set(CodiraCore_ENABLE_BACKDEPLOYMENT_SUPPORT ON CACHE BOOL "")
set(CodiraCore_ENABLE_FILESYSTEM_SUPPORT ON CACHE BOOL "")
set(CodiraCore_ENABLE_STRICT_AVAILABILITY ON CACHE BOOL "")

set(CodiraCore_OPTIMIZATION_REMARKS "bitstream" CACHE STRING "")

set(CodiraCore_INSTALL_NESTED_SUBDIR OFF CACHE BOOL "")

set(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -g -DNDEBUG" CACHE STRING "")
set(CMAKE_C_FLAGS_MINSIZEREL "-Os -g -DNDEBUG" CACHE STRING "")
set(CMAKE_Codira_FLAGS_MINSIZEREL "-Osize -g" CACHE STRING "")
