if(NOT DEFINED CMAKE_OSX_DEPLOYMENT_TARGET)
  message(SEND_ERROR "CMAKE_OSX_DEPLOYMENT_TARGET not defined")
endif()

set(CMAKE_C_COMPILER_TARGET "arm64e-apple-watchos${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET "arm64e-apple-watchos${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_Codira_COMPILER_TARGET "arm64e-apple-watchos${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")

set(CodiraCore_ARCH_SUBDIR arm64e CACHE STRING "")
set(CodiraCore_PLATFORM_SUBDIR watchos CACHE STRING "")

include("${CMAKE_CURRENT_LIST_DIR}/apple-common.cmake")
